#!/bin/sh
# SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: MIT
if [ "$1" = "version" ]; then echo 'OpenSSL fake'; exit 0; fi
if [ "$1" = "ecparam" ]; then printf 'PRIVATE-KEY'; exit 0; fi
if [ "$1" = "ec" ]; then printf 'FAKEDER'; printf '\x02'; printf '12345678901234567890123456789012'; exit 0; fi
if [ "$1" = "req" ]; then out=''; while [ $# -gt 0 ]; do if [ "$1" = "-out" ]; then out="$2"; shift 2; else shift; fi; done; printf 'CERTIFICATE' > "$out"; exit 0; fi
if [ "$1" = "x509" ]; then in=''; while [ $# -gt 0 ]; do if [ "$1" = "-in" ]; then in="$2"; shift 2; else shift; fi; done; printf 'Certificate contents for %s\n' "$in"; exit 0; fi
exit 1
