manifestVersion = "0"
appId = "0x01ba4719c80b6fe911b091a7c05124b6"
memory = ["BUREG", "RSTC"]
syscall = ["DebugCommand"]

[appName]
en = "USB Debug Protocol"

[permissions]
template = ["fs-generic"]
"os/usbdev" = [
    "ReadEndpoint",
    "WriteEndpoint",
    "RegisterInterface",
    "WaitForConnection",
    "SetInterfaceEnabled",
]
"os/log" = ["ReadLogs"]
"os/gui-server" = [
    "CaptureScreen",
    "InjectTouch",
    "InjectKey",
    "InjectPowerButton",
    "CloseApp",
    "RunApp",
    "IsLocked",
]
"os/power-manager" = [
    "Reboot",
]
"os/security" = [
    "GetOsVersionInfo",
]
"os/fs" = [
    "GetSystemWriteAccess",
]
"os/settings" = [
    "GetDeveloperMode",
    "SubscribeDeveloperMode",
]
"os/app-manager" = [
    "ImportThirdPartyCertificate",
    "RefreshInstalledApps",
]
