[mcp_servers.passport-drive]
args = [
    "develop",
    "--command",
    "cargo",
    "run",
    "-p",
    "passport-drive",
    "--release",
    "--",
    "mcp",
]
command = "nix"
cwd = "."

[mcp_servers.passport-drive.tools.list_ports]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.connect]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.screenshot]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.disconnect]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.input_text]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.get_logs]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.get_process_list]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.send_kernel_command]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.get_version]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.get_developer_mode]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.load_app]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.launch_app]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.clear_logs]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.close_app]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.tap]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.power_button]
approval_mode = "approve"

[mcp_servers.passport-drive.tools.swipe]
approval_mode = "approve"
