# SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

appId = "0x04c4f26ff3e6398c1e521057c4c0a596"

[appName]
en = "Monero"

[appDescription]
en = "Monero app running on Flux."

[permissions]
"os/gui-app-emu-flux" = ["SvcCall", "SendSeph", "RecvSeph", "SyscallBuffer"]
