manifestVersion = "0"
appId = "0x6F732F75706461746500000000000000"
syscall = ["SetThreadPriority"]

[appName]
en = "Update Server"

[servers."os/update"]
SubscribeUpdateProgress = { id = 0, type = "archiveEvent", approval = "autoAllow" }
StartUpdate = { id = 1, type = "archive", approval = "autoAllow" }
ContinueUpdate = { id = 2, type = "archive", approval = "autoAllow" }
DownloadStallTick = { id = 3, type = "scalar" }
FirmwareVersion = { id = 4, type = "blockingArchive", approval = "autoAllow" }
ApplyDownloadedUpdate = { id = 5, type = "archive", approval = "autoAllow" }
GetUpdateApplied = { id = 6, type = "blockingScalar", approval = "autoAllow" }
ClearUpdateApplied = { id = 7, type = "scalar", approval = "autoAllow" }
GetUpdateStatus = { id = 8, type = "blockingArchive", approval = "autoAllow" }
FirmwareInstallWorkerEvent = { id = 9, type = "archive", cfg = "keyos" }

[permissions]
template = ["fs-generic", "crypto-sha"]
"os/fs" = [
    "GetSystemReadAccess",
    "GetSystemWriteAccess",
    "GetSystemAppDataReadAccess",
    "GetSystemAppDataWriteAccess",
    "FlushFs",
]
"os/power-manager-ext" = ["GetStatus"]
"os/quantum-link" = ["SubscribeFirmwareFetch", "StartFirmwareUpdate"]
"os/gui-server" = ["Shutdown"]
"os/security" = ["GetFirmwareTimestamp", "SetFirmwareTimestamp"]
