manifestVersion = "0"
appId = "0xc192b79230473875f159d4423d74d00f"

[appName]
en = "Settings"

[permissions]
template = ["gui-app", "fs-generic"]
"os/app-manager" = [
    "LaunchAppBlocking",
    "ListApps",
    "GetAppIcon",
    "GetThirdPartyCertificates",
    "ImportThirdPartyCertificate",
    "RemoveThirdPartyCertificate",
    "RemoveInstalledApp",
]
"os/backup" = ["StatusSubscribe", "CreateBackup", "CreateBackupFile"]
"os/bt" = ["GetBleVersionInfo", "SubscribeBleState", "GetBtAddr"]
"os/power-manager-ext" = [
    "GetStatus",
    "GetExtendedStatus",
    "StatusSubscribe",
]
"os/security" = [
    "ChangePin",
    "GetOsVersionInfo",
    "GetDeviceId",
    "Lockout",
    "GetSeed",
    "GetPinEntryMode",
    "GetSeedFingerprint",
]
"os/fs" = [
    "GetAirlockReadAccess",
    "GetAirlockWriteAccess",
    "GetSystemWriteAccess",
    "GetUserReadAccess",
    "GetUserWriteAccess",
    "GetUsbReadAccess",
    "GetUsbWriteAccess",
]
"os/gui-server" = ["SwitchTo", "SwitchToLauncher", "UpdateKioskPolicy", "ClaimSettingsRole"]
"os/settings" = [
    "GetTimeZone",
    "SetTimeZone",
    "LookupTimeZone",
    "ListTimeZone",
    "SetScreenBrightness",
    "SubscribeScreenBrightness",
    "SetSystemTheme",
    "GetDeviceName",
    "SetDeviceName",
    "SubscribeDeviceName",
    "GetAutoLock",
    "SetAutoLock",
    "GetShowSecurityWords",
    "SetShowSecurityWords",
    "GetUseStandardTimeFormat",
    "SetUseStandardTimeFormat",
    "GetEnvoyTimeSync",
    "SetEnvoyTimeSync",
    "GetMagicBackupEnabled",
    "SetMagicBackupEnabled",
    "SetDeveloperMode",
    "SubscribeDeveloperMode",
    "GetLocale",
    "GetPrimeColor",
    "GetOnboardingStatus",
    "SubscribeMagicBackupEnabled",
]
"os/quantum-link" = [
    "GetXidDocument",
    "SubscribePairingEvent",
    "UnpairFromEnvoy",
    "SendPrimeMagicBackupEnabled",
    "SubscribeConnectionStatus",
    "EnvoyTimezone",
    "StartFirmwareUpdate",
    "CheckFirmwareUpdate",
    "NotifyFirmwareInstall",
    "RestoreShard",
    "BackupShard",
]
"os/update" = [
    "ApplyDownloadedUpdate",
    "ClearUpdateApplied",
    "ContinueUpdate",
    "FirmwareVersion",
    "GetUpdateApplied",
    "GetUpdateStatus",
    "StartUpdate",
    "SubscribeUpdateProgress",
]
"os/keycard" = [
    "IdentifyKeycard",
    "GenerateShards",
    "PopShard",
    "PushShard",
    "ResetShards",
    "LoadShardFromKeycard",
    "StoreShardToKeycard",
    "RestoreMasterSeed",
    "DetectKeycard",
    "CheckBackup",
    "SetShamirScheme",
]
"os/haptics" = ["Vibrate"]
"os/ticktimer" = ["SetSystemTime"]
