// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

//! NBGL display framebuffer and draw primitives.
//!
//! The server thread writes into a shared word-pixel framebuffer via `draw_rect`,
//! `draw_horizontal_line`, and `draw_image`. On `NbglRefresh` the buffer is
//! snapshotted and passed to the registered callback.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{LazyLock, OnceLock, RwLock};

use ab_glyph::{Font, FontRef, ScaleFont};

use super::{NbglArea, SephTag, SEPH_FIFO};

pub const DISPLAY_WIDTH: usize = 480;
pub const DISPLAY_HEIGHT: usize = 600;
const PIXEL_COUNT: usize = DISPLAY_WIDTH * DISPLAY_HEIGHT;
/// RGB888 display pixel in `0x00RRGGBB` format.
pub type FramePixel = u32;
pub type Frame = Vec<FramePixel>;
type Pixel = FramePixel;

const WHITE: Pixel = 0x00FF_FFFF;
const DARK_BACKGROUND: Pixel = 0x0021_2121;

/// Shared RGB888 framebuffer. Server thread writes, `refresh()` reads.
static DISPLAY_BUFFER: LazyLock<RwLock<Vec<Pixel>>> = LazyLock::new(|| RwLock::new(vec![WHITE; PIXEL_COUNT]));

/// Dark mode state, pushed from the Slint event loop via `set_dark_mode()`.
/// Using an AtomicBool so background threads (flux server, app monitor) can
/// read it safely without going back through Slint's property system.
static IS_DARK_MODE: AtomicBool = AtomicBool::new(false);

/// Update the dark mode state. Must be called from the Slint event loop
/// at startup and whenever the theme changes.
pub fn set_dark_mode(dark: bool) { IS_DARK_MODE.store(dark, Ordering::Relaxed); }

/// Callback invoked to push a new display frame.
/// Set once from the binary crate via `init()`.
static REFRESH_CALLBACK: OnceLock<Box<dyn Fn(Frame) + Send + Sync>> = OnceLock::new();

/// Callback invoked after `reset()` clears the display.
static RESET_CALLBACK: OnceLock<Box<dyn Fn() + Send + Sync>> = OnceLock::new();

/// Register the callback that receives refreshed display images.
///
/// The callback is invoked on the caller's thread each time `NbglRefresh`
/// fires. UI callers must dispatch the callback body to their UI runtime.
pub fn init(cb: impl Fn(Frame) + Send + Sync + 'static) {
    if REFRESH_CALLBACK.set(Box::new(cb)).is_err() {
        log::warn!("display::init called more than once");
    }
}

/// Fill a rectangle in the framebuffer. `color` is `0x00RRGGBB`.
pub fn draw_rect(x0: u16, y0: u16, width: u16, height: u16, color: u32) {
    let Ok(mut buf) = DISPLAY_BUFFER.write() else {
        log::warn!("draw_rect: could not acquire write lock");
        return;
    };

    let pixel = color_to_pixel(color);
    let x_start = (x0 as usize).min(DISPLAY_WIDTH);
    let y_start = (y0 as usize).min(DISPLAY_HEIGHT);
    let x_end = ((x0 as usize) + (width as usize)).min(DISPLAY_WIDTH);
    let y_end = ((y0 as usize) + (height as usize)).min(DISPLAY_HEIGHT);

    for y in y_start..y_end {
        let row_offset = y * DISPLAY_WIDTH;
        buf[row_offset + x_start..row_offset + x_end].fill(pixel);
    }
}

/// Draw a 1-pixel horizontal line.

/// Decode a packed NBGL bitmap and blit it into the framebuffer.
///
/// `bpp` is the *real* bits-per-pixel (1, 2, or 4) after `nbgl_bpp_to_read_bpp`.
/// `color_map` encodes foreground/background grayscale levels.
/// `transformation`: 0x00 = none, 0x02 = vertical mirror, 0x04 = rotate 90° CW.
///
/// Pixel data is in **column-first, right-to-left** order as generated by
/// the SDK's `icon2glyph.py`. The column-first layout is transposed to
/// row-major screen coordinates during blitting, matching `draw_image_rle`.
pub(crate) fn draw_image(area: NbglArea, bpp: u8, transformation: u8, buffer: &[u8], color_map: u8) {
    let w = area.width as usize;
    let h = area.height as usize;

    if w == 0 || h == 0 {
        return;
    }

    if buffer.is_empty() {
        return;
    }

    // Decode all pixels into a word-pixel buffer (column-first order).
    let total_pixels = w * h;
    let mut pixels = Vec::with_capacity(total_pixels);

    match bpp {
        1 => decode_1bpp(buffer, total_pixels, color_map, area.color, &mut pixels),
        2 => decode_2bpp(buffer, total_pixels, color_map, &mut pixels),
        4 => decode_4bpp(buffer, total_pixels, color_map, area.color, &mut pixels),
        _ => {
            log::warn!("draw_image: unsupported bpp={bpp}");
            return;
        }
    }

    // Apply transformation and blit with column-first transpose.
    let Ok(mut buf) = DISPLAY_BUFFER.write() else {
        log::warn!("draw_image: could not acquire write lock");
        return;
    };

    let x0 = area.x0 as usize;
    let y0 = area.y0 as usize;

    match transformation {
        0x00 => {
            // Column-first RTL → screen coordinates (same as draw_image_rle).
            blit_column_first(&mut buf, x0, y0, w, h, &pixels);
        }
        0x02 => {
            // VERTICAL_MIRROR: mirror about the vertical axis = horizontal flip (swap left/right).
            // Normal blit maps column-first (col, row) → screen (x0 + w-1-col, y0 + row).
            // Horizontal flip reverses x: (col, row) → screen (x0 + col, y0 + row).
            let mut pixel_idx = 0;
            let mut col = 0;
            let mut row = 0;
            while pixel_idx < pixels.len() {
                let dx = x0 + col;
                let dy = y0 + row;
                if dx < DISPLAY_WIDTH && dy < DISPLAY_HEIGHT {
                    let dst = dy * DISPLAY_WIDTH + dx;
                    buf[dst] = pixels[pixel_idx];
                }
                pixel_idx += 1;
                row += 1;
                if row >= h {
                    row = 0;
                    col += 1;
                }
            }
        }
        0x04 => {
            // Rotate 90° CW from column-first input.
            // Column-first pixel (col, row) → original screen pos (w-1-col, row).
            // After 90° CW rotation: (x, y) → (h-1-y, x), output is h×w.
            // Combined: column-first (col, row) → rotated screen (h-1-row, w-1-col).
            let mut pixel_idx = 0;
            let mut col = 0;
            let mut row = 0;
            while pixel_idx < pixels.len() {
                let dx = x0 + (h - 1 - row);
                let dy = y0 + (w - 1 - col);
                if dx < DISPLAY_WIDTH && dy < DISPLAY_HEIGHT {
                    let dst = dy * DISPLAY_WIDTH + dx;
                    buf[dst] = pixels[pixel_idx];
                }
                pixel_idx += 1;
                row += 1;
                if row >= h {
                    row = 0;
                    col += 1;
                }
            }
        }
        _ => {
            log::warn!(
                "draw_image: unsupported transformation=0x{transformation:02x}, drawing without transform"
            );
            blit_column_first(&mut buf, x0, y0, w, h, &pixels);
        }
    }
}

/// Snapshot the buffer and pass it to the registered refresh callback.
///
/// Light mode: clone the word-pixel buffer.
/// Dark mode: invert while snapshotting.
pub fn refresh() {
    let Some(cb) = REFRESH_CALLBACK.get() else {
        log::warn!("display::refresh: callback not set (call display::init first)");
        return;
    };

    let is_dark = IS_DARK_MODE.load(Ordering::Relaxed);
    let Some(frame) = snapshot_frame("display::refresh", is_dark) else {
        return;
    };
    cb(frame);
}

/// Register a callback invoked after `reset()` clears the display.
///
/// The callback is invoked on the caller's thread. UI callers must dispatch
/// the callback body to their UI runtime.
pub fn on_reset(cb: impl Fn() + Send + Sync + 'static) {
    if RESET_CALLBACK.set(Box::new(cb)).is_err() {
        log::warn!("display::on_reset called more than once");
    }
}

/// Clear the framebuffer and notify the reset callback.
///
/// Called from the server thread when the Flux app process disconnects.
pub fn reset() {
    clear();

    if let Some(refresh_cb) = REFRESH_CALLBACK.get() {
        if let Some(frame) = snapshot_frame("display::reset", false) {
            refresh_cb(frame);
        }
    }
    if let Some(reset_cb) = RESET_CALLBACK.get() {
        reset_cb();
    }
}

/// Fill buffer with the background color: white in light mode, #212121 in dark mode.
pub fn clear() {
    if let Ok(mut buf) = DISPLAY_BUFFER.write() {
        let is_dark = IS_DARK_MODE.load(Ordering::Relaxed);
        if is_dark {
            buf.fill(DARK_BACKGROUND);
        } else {
            buf.fill(WHITE);
        }
    }
}

/// Build a SEPH FingerEvent TLV and push it to `SEPH_FIFO`.
///
/// Format: `[0x0c, 0x00, 0x05, state, x_hi, x_lo, y_hi, y_lo]`
/// State: 1 = pressed, 0 = released.
pub fn push_touch_event(x: i16, y: i16, state: u8) {
    let x_bytes = x.to_be_bytes();
    let y_bytes = y.to_be_bytes();
    let pkt =
        vec![SephTag::FingerEvent.into(), 0x00, 0x05, state, x_bytes[0], x_bytes[1], y_bytes[0], y_bytes[1]];

    if let Ok(mut fifo) = SEPH_FIFO.write() {
        log::trace!(
            "push_touch_event: x={x}, y={y}, state={state}, pkt={pkt:02x?}, fifo_len={}",
            fifo.len() + 1
        );
        fifo.push_back(pkt);
    } else {
        log::error!("push_touch_event: failed to acquire SEPH_FIFO write lock");
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

#[inline]
fn color_to_pixel(color: u32) -> Pixel { color & 0x00FF_FFFF }

#[inline]
fn gray_to_pixel(gray: u8) -> Pixel {
    let gray = gray as Pixel;
    (gray << 16) | (gray << 8) | gray
}

#[inline]
fn invert_pixel(pixel: Pixel) -> Pixel {
    let r = 0xFF - ((pixel >> 16) & 0xFF);
    let g = 0xFF - ((pixel >> 8) & 0xFF);
    let b = 0xFF - (pixel & 0xFF);

    // Avoid pure black after inversion — use #212121 as the darkest background.
    if r == 0 && g == 0 && b == 0 {
        DARK_BACKGROUND
    } else {
        (r << 16) | (g << 8) | b
    }
}

fn snapshot_frame(context: &str, invert: bool) -> Option<Frame> {
    let Ok(buf) = DISPLAY_BUFFER.read() else {
        log::warn!("{context}: could not acquire read lock");
        return None;
    };
    if invert {
        Some(buf.iter().copied().map(invert_pixel).collect())
    } else {
        Some(buf.clone())
    }
}

/// Blit a word-pixel buffer (row-major order) into the display framebuffer at (x0, y0).
/// Retained for future use (e.g. QR codes which produce row-major data).
#[allow(dead_code)]
fn blit(buf: &mut [Pixel], x0: usize, y0: usize, w: usize, h: usize, pixels: &[Pixel]) {
    for row in 0..h {
        let dy = y0 + row;
        if dy >= DISPLAY_HEIGHT {
            break;
        }
        for col in 0..w {
            let dx = x0 + col;
            if dx >= DISPLAY_WIDTH {
                break;
            }
            let src = row * w + col;
            let dst = dy * DISPLAY_WIDTH + dx;
            if src < pixels.len() {
                buf[dst] = pixels[src];
            }
        }
    }
}

/// Blit column-first RTL pixel data into the framebuffer.
///
/// Pixel data is in column-first, right-to-left order (as produced by
/// `icon2glyph.py`): the first pixel corresponds to the bottom of the
/// rightmost column, advancing top-to-bottom within each column, then
/// moving right-to-left across columns.
fn blit_column_first(buf: &mut [Pixel], x0: usize, y0: usize, w: usize, h: usize, pixels: &[Pixel]) {
    let total_pixels = pixels.len();
    let mut pixel_idx = 0;
    let mut col = 0;
    let mut row = 0;
    while pixel_idx < total_pixels {
        let dx = x0 + (w - 1 - col);
        let dy = y0 + row;
        if dx < DISPLAY_WIDTH && dy < DISPLAY_HEIGHT {
            let dst = dy * DISPLAY_WIDTH + dx;
            buf[dst] = pixels[pixel_idx];
        }
        pixel_idx += 1;
        row += 1;
        if row >= h {
            row = 0;
            col += 1;
        }
    }
}

/// Convert a 2-bit NBGL grayscale level to an 8-bit value.
/// 0 → 0 (black), 1 → 85, 2 → 170, 3 → 255 (white).
fn gray_level_to_u8(level: u8) -> u8 { (level & 0x03) * 85 }

/// 1bpp: bit=1 → foreground (color_map & 0x03), bit=0 → background (area.color).
/// MSB first within each byte.
/// Note: the SDK's icon2glyph.py inverts 1bpp images before packing, so
/// bit=0 corresponds to the original white (background) pixels and bit=1
/// to the original black (foreground) pixels.
fn decode_1bpp(buffer: &[u8], total_pixels: usize, color_map: u8, bg_color: u8, out: &mut Vec<Pixel>) {
    let fg = gray_level_to_u8(color_map & 0x03);
    let bg = gray_level_to_u8(bg_color & 0x03);

    let mut pixel_count = 0;
    for &byte in buffer {
        for bit_idx in (0..8).rev() {
            if pixel_count >= total_pixels {
                return;
            }
            let bit = (byte >> bit_idx) & 1;
            let g = if bit == 1 { fg } else { bg };
            out.push(gray_to_pixel(g));
            pixel_count += 1;
        }
    }
}

/// 2bpp: 2 bits per pixel → index 0-3. Mapped via color_map (2 bits per entry, MSB first).
fn decode_2bpp(buffer: &[u8], total_pixels: usize, color_map: u8, out: &mut Vec<Pixel>) {
    let mut pixel_count = 0;
    for &byte in buffer {
        for shift in (0..8).step_by(2).rev() {
            if pixel_count >= total_pixels {
                return;
            }
            let idx = (byte >> shift) & 0x03;
            // color_map has 4 entries of 2 bits each, packed MSB first:
            // bits 7-6 = index 0, bits 5-4 = index 1, bits 3-2 = index 2, bits 1-0 = index 3
            let mapped = (color_map >> (6 - idx * 2)) & 0x03;
            let g = gray_level_to_u8(mapped);
            out.push(gray_to_pixel(g));
            pixel_count += 1;
        }
    }
}

/// 4bpp: 4 bits per pixel → 16 levels, interpolated between foreground and background colors.
/// val=0 → foreground, val=15 → background. MSB first.
fn decode_4bpp(buffer: &[u8], total_pixels: usize, color_map: u8, bg_color: u8, out: &mut Vec<Pixel>) {
    let fg = gray_level_to_u8(color_map & 0x03) as u16;
    let bg = gray_level_to_u8(bg_color & 0x03) as u16;
    let mut pixel_count = 0;
    for &byte in buffer {
        for shift in [4, 0] {
            if pixel_count >= total_pixels {
                return;
            }
            let val = (byte >> shift) & 0x0F;
            let g = (fg * (15 - val as u16) + bg * val as u16) / 15;
            out.push(gray_to_pixel(g as u8));
            pixel_count += 1;
        }
    }
}

/// Decode RLE-compressed image data and blit into the framebuffer.
///
/// Pixels are decoded in **column-first** order (right-to-left columns,
/// top-to-bottom within each column) — the layout used by NBGL's
/// `box_to_packed_bitmap(nbgl=true)` encoder. After decoding, pixels are
/// transposed to row-major order for the framebuffer blit.
///
/// `nb_skipped_bytes` skips that many decoded pixels from the start
/// (used for partial character rendering).
pub(crate) fn draw_image_rle(area: NbglArea, bpp: u8, fore_color: u8, buffer: &[u8], nb_skipped_bytes: u8) {
    let w = area.width as usize;
    let h = area.height as usize;

    if w == 0 || h == 0 {
        return;
    }

    let total_pixels = w * h;

    // Zero-length buffer (e.g. space characters): fill with background color.
    if buffer.is_empty() {
        let bg = gray_level_to_u8(area.color & 0x03);
        draw_rect(area.x0, area.y0, area.width, area.height, gray_to_pixel(bg));
        return;
    }

    // Decode RLE into a flat pixel array (column-first order).
    let decoded = match bpp {
        1 => decode_rle_1bpp(buffer, total_pixels, fore_color, area.color),
        4 => decode_rle_4bpp(buffer, total_pixels),
        _ => {
            log::warn!("draw_image_rle: unsupported bpp={bpp}");
            return;
        }
    };

    // Skip pixels (the C code names the param nb_skipped_bytes but the
    // value is computed as a pixel count by the SDK).
    let skip = nb_skipped_bytes as usize;

    // Transpose column-first → row-major and blit.
    let Ok(mut buf) = DISPLAY_BUFFER.write() else {
        log::warn!("draw_image_rle: could not acquire write lock");
        return;
    };

    let mut pixel_idx = skip;
    // Column-first order: col goes from (width-1) down to 0,
    // row goes from 0 up to (height-1) within each column.
    let start_col = pixel_idx / h;
    let start_row = pixel_idx % h;

    let mut col = start_col;
    let mut row = start_row;

    while pixel_idx < decoded.len() && col < w {
        let g = decoded[pixel_idx];
        // Transpose: column-first right-to-left → screen coordinates
        let dx = area.x0 as usize + (w - 1 - col);
        let dy = area.y0 as usize + row;

        if dx < DISPLAY_WIDTH && dy < DISPLAY_HEIGHT {
            let dst = dy * DISPLAY_WIDTH + dx;
            buf[dst] = gray_to_pixel(g);
        }

        pixel_idx += 1;
        row += 1;
        if row >= h {
            row = 0;
            col += 1;
        }
    }
}

/// 1bpp RLE decode: each byte = `ZZZZOOOO`
/// - ZZZZ (high nibble): count of 0-pixels (background color)
/// - OOOO (low nibble): count of 1-pixels (foreground/ink color)
fn decode_rle_1bpp(buffer: &[u8], total_pixels: usize, fore_color: u8, bg_color: u8) -> Vec<u8> {
    let fg = gray_level_to_u8(fore_color & 0x03);
    let bg = gray_level_to_u8(bg_color & 0x03);
    let mut pixels = Vec::with_capacity(total_pixels);

    for &byte in buffer {
        let zeros = (byte >> 4) & 0x0F;
        let ones = byte & 0x0F;

        for _ in 0..zeros {
            if pixels.len() >= total_pixels {
                return pixels;
            }
            pixels.push(bg); // 0-pixel = background
        }
        for _ in 0..ones {
            if pixels.len() >= total_pixels {
                return pixels;
            }
            pixels.push(fg); // 1-pixel = foreground/ink
        }
    }

    // Pad remaining pixels with background if the RLE data is shorter
    while pixels.len() < total_pixels {
        pixels.push(bg);
    }
    pixels
}

/// 4bpp RLE decode. Three byte types:
/// - `0CCCNNNN` (bit7=0): non-white run of CCC+1 pixels of color NNNN
/// - `10PPXXXX` (bits7-6=10): packed singles, PP+3 total pixels (3-6), first pixel = XXXX nibble, remaining
///   packed 2-per-byte after
/// - `11CCCCCC` (bits7-6=11): white run of CCCCCC+1 pixels (color 15)
fn decode_rle_4bpp(buffer: &[u8], total_pixels: usize) -> Vec<u8> {
    let mut pixels = Vec::with_capacity(total_pixels);
    let mut i = 0;

    while i < buffer.len() && pixels.len() < total_pixels {
        let byte = buffer[i];
        i += 1;

        if byte & 0x80 == 0 {
            // Non-white run: 0CCCNNNN
            let count = ((byte >> 4) & 0x07) as usize + 1; // CCC + 1 (1-8)
            let color = byte & 0x0F;
            let g = color * 17;
            for _ in 0..count {
                if pixels.len() >= total_pixels {
                    break;
                }
                pixels.push(g);
            }
        } else if byte & 0xC0 == 0x80 {
            // Packed singles: 10PPXXXX
            let num_pixels = ((byte >> 4) & 0x03) as usize + 3; // PP + 3 (3-6)
            let first_nibble = byte & 0x0F;
            // We have num_pixels total. First pixel is the XXXX nibble.
            // Remaining nibbles are packed 2-per-byte in subsequent bytes.
            let mut nibbles = Vec::with_capacity(num_pixels);
            nibbles.push(first_nibble);
            // Read remaining nibbles from subsequent bytes
            let remaining = num_pixels - 1;
            let bytes_needed = remaining.div_ceil(2);
            for _ in 0..bytes_needed {
                if i >= buffer.len() {
                    break;
                }
                let b = buffer[i];
                i += 1;
                nibbles.push((b >> 4) & 0x0F);
                nibbles.push(b & 0x0F);
            }
            for j in 0..num_pixels {
                if pixels.len() >= total_pixels || j >= nibbles.len() {
                    break;
                }
                pixels.push(nibbles[j] * 17);
            }
        } else {
            // White run: 11CCCCCC
            let count = (byte & 0x3F) as usize + 1; // CCCCCC + 1 (1-64)
            for _ in 0..count {
                if pixels.len() >= total_pixels {
                    break;
                }
                pixels.push(255); // white = color 15 = 15*17 = 255
            }
        }
    }

    // Pad with white if needed
    while pixels.len() < total_pixels {
        pixels.push(255);
    }
    pixels
}

// ---------------------------------------------------------------------------
// Native text rendering using ab_glyph (host/simulator only)
// ---------------------------------------------------------------------------

static FONT_MONTSERRAT_REGULAR: &[u8] = include_bytes!("../../../../ui/ui/fonts/Montserrat-Regular.ttf");
static FONT_MONTSERRAT_MEDIUM: &[u8] = include_bytes!("../../../../ui/ui/fonts/Montserrat-Medium.ttf");

/// Map NBGL font ID to (font data, pixel size).
///
/// NBGL font IDs (for Flux target):
///   11 = Regular 28px (4bpp)     → height 36
///   12 = SemiBold 28px (4bpp)    → height 36 (mapped to Montserrat Medium)
///   13 = Medium 36px (4bpp)      → height 44
///   14 = Regular 28px 1bpp       → height 36
///   15 = SemiBold 28px 1bpp      → height 36 (mapped to Montserrat Medium)
///   16 = Medium 36px 1bpp        → height 44
fn font_for_id(font_id: u8) -> (&'static [u8], f32) {
    match font_id {
        11 | 14 => (FONT_MONTSERRAT_REGULAR, 32.0),
        12 | 15 => (FONT_MONTSERRAT_MEDIUM, 32.0),
        13 | 16 => (FONT_MONTSERRAT_MEDIUM, 42.0),
        _ => {
            log::warn!("draw_text_native: unknown font_id={font_id}, defaulting to Montserrat Regular 32px");
            (FONT_MONTSERRAT_REGULAR, 32.0)
        }
    }
}

/// Render text natively using ab_glyph, bypassing the NBGL bitmap pipeline.
pub(crate) fn draw_text_native(area: NbglArea, font_id: u8, font_color: u8, text: &str) {
    let (font_data, px_size) = font_for_id(font_id);
    let Ok(font) = FontRef::try_from_slice(font_data) else {
        log::warn!("draw_text_native: failed to parse font data for id={font_id}");
        return;
    };

    let fg = gray_level_to_u8(font_color & 0x03);

    let scaled = font.as_scaled(px_size);
    let ascent = scaled.ascent();

    let Ok(mut buf) = DISPLAY_BUFFER.write() else {
        return;
    };

    let mut cursor_x = area.x0 as f32;
    let baseline_y = area.y0 as f32 + ascent;
    let mut last_glyph_id = None;

    for ch in text.chars() {
        // Skip NBGL control characters
        if ch == '\x08' || ch == '\x0c' {
            continue;
        }

        let glyph_id = scaled.glyph_id(ch);

        // Apply kerning
        if let Some(last) = last_glyph_id {
            cursor_x += scaled.kern(last, glyph_id);
        }

        // Rasterize the glyph
        let glyph = ab_glyph::Glyph {
            id: glyph_id,
            scale: px_size.into(),
            position: ab_glyph::point(cursor_x, baseline_y),
        };

        if let Some(outlined) = font.outline_glyph(glyph) {
            let bounds = outlined.px_bounds();
            outlined.draw(|rx, ry, coverage| {
                let px = bounds.min.x as i32 + rx as i32;
                let py = bounds.min.y as i32 + ry as i32;
                if px < 0 || py < 0 {
                    return;
                }
                let dx = px as usize;
                let dy = py as usize;
                if dx >= DISPLAY_WIDTH || dy >= DISPLAY_HEIGHT {
                    return;
                }
                let dst = dy * DISPLAY_WIDTH + dx;
                // Alpha-blend foreground onto background
                let alpha = (coverage * 255.0) as u16;
                let inv = 255 - alpha;
                let background = ((buf[dst] >> 16) & 0xFF) as u16;
                let blended = ((fg as u16 * alpha + background * inv) / 255) as u8;
                buf[dst] = gray_to_pixel(blended);
            });
        }

        cursor_x += scaled.h_advance(glyph_id);
        last_glyph_id = Some(glyph_id);
    }
}
