// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

import { ViewSeedWordsProps } from "props.slint";
import { BasePage } from "@ui/widgets.slint";
import { ViewSeed } from "@ui/pages.slint";
import { Navigate } from "../../../../gen/navigate.slint";
import { TR2, TrId } from "../../../../gen/tr.slint";
import { Callbacks } from "../../../../callbacks.slint";

export component ViewSeedWordsPage inherits BasePage {
    in property <ViewSeedWordsProps> props;

    ViewSeed {
        words: Callbacks.get-seed-words();
        standard-qr: Callbacks.get-standard-seed-qr();
        compact-qr: Callbacks.get-compact-seed-qr();
        strings: {
            title: TR2.lookup(TrId.ViewSeedWordsTitle),
            standard-qr-header: TR2.lookup(TrId.ViewSeedWordsStandardSeedQr),
            compact-qr-header: TR2.lookup(TrId.ViewSeedWordsCompactSeedQr),
            done: TR2.lookup(TrId.CommonButtonDone),
        };
        back => {
            Navigate.backward();
        }
    }
}
