// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Size, Palette } from "@ui/theme.slint";
import { Checkbox } from "./checkbox.slint";
import { TextSm } from "./txt.slint";

export struct CheckboxGroupModel {
    name: string,
    value: string,
    checked: bool,
    enabled: bool,
}

export component CheckboxGroup inherits VerticalLayout {
    spacing: Size.sz4;

    // Public properties
    in-out property <[CheckboxGroupModel]> model: [];
    in property <bool> label-right;
    in property <bool> disabled-labels-dimmed: false;
    in property <length> horizontal-spacing: Size.sz6;

    // Callbacks
    callback changed(int, string);

    function item-changed(index: int, value: string) {
        model[index].checked = !model[index].checked;
        changed(index, value);
    }

    for entry[index] in model: Rectangle {
        HorizontalLayout {
            spacing: horizontal-spacing;
            if !label-right: TextSm {
                text: entry.name;
                color: root.disabled-labels-dimmed && !entry.enabled ? Palette.content-disabled : Palette.content-primary;
                vertical-alignment: TextVerticalAlignment.center;
            }
            Checkbox {
                controlled: true;
                checked: entry.checked;
                enabled: entry.enabled;
            }

            if label-right: TextSm {
                text: entry.name;
                color: root.disabled-labels-dimmed && !entry.enabled ? Palette.content-disabled : Palette.content-primary;
                vertical-alignment: TextVerticalAlignment.center;
            }
        }

        TouchArea {
            enabled: entry.enabled;
            clicked => {
                item-changed(index, entry.value);
            }
        }
    }
}
