// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later


import { Circle } from "./circle.slint";
import { Icon } from "./icon.slint";
import { Timings, Images, Palette, Size } from "@ui/theme.slint";

export component RadioButton inherits Rectangle {
    // Override inherited properties
    width: Size.sz7;
    height: Size.sz7;
    clip: true;

    // Private properties
    private property <brush> bg-color: checked ? Palette.background-brand : Palette.background-primary;
    private property <brush> radio-border-color: checked ? Palette.transparent : Palette.border-primary;

    // Public properties
    in property <string> id;
    in property <bool> enabled: true;
    in property <bool> controlled: false;
    in-out property <bool> checked;

    // Callbacks
    callback clicked(string);

    Circle {
        background: bg-color;
        border-color: root.radio-border-color;
        border-width: checked ? Size.zero : Size.sz0_5;
        size: root.width;
        animate background {
            duration: Timings.prop-change;
            easing: ease-in-out;
        }

        Icon {
            name: "check";
            color: root.enabled ? Palette.border-inverse : Palette.content-disabled;
            size: Size.sz6;
            opacity: checked ? 1 : 0;

            animate size { duration: Timings.prop-change; }
            animate opacity { duration: Timings.prop-change; }
        }

        states [
            disabled when !root.enabled: {
                background: Palette.background-disabled;
                border-color: checked ? Palette.transparent : Palette.border-disabled;
            }
            pressed when touchArea.pressed && enabled && checked: {
                background: Palette.background-brand-pressed;
            }
        ]
    }

    touchArea := TouchArea {
        clicked => {
            if (enabled) {
                if (!controlled) {
                    checked = !checked;
                }
                clicked(id);
            }
        }
    }
}
