// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { IconSize, Palette } from "@ui/theme.slint";
import { JumboIcon } from "./jumbo-icon.slint";
import { Icon } from "./icon.slint";

export component WrappedIcon inherits JumboIcon {
    // "jumbo-circle", "jumbo-shield", "jumbo-underbar"
    in property <string> outer-icon: "jumbo-circle";
    in property <string> inner-icon: "check";
    in property <bool> compact: false;
    private property <length> inner-icon-size: min(
        compact ? IconSize.px64 : IconSize.px96,
        compact ? root.height / 2 : root.height * 96 / 184,
    );

    name: compact && outer-icon == "jumbo-circle" ? "compact-circle" : outer-icon;

    Rectangle {
        width: root.inner-icon-size;
        height: root.inner-icon-size;
        clip: false;

        Icon {
            name: root.inner-icon;
            size: parent.width;
            color: Palette.content-brand;
        }
    }
}
