manifestVersion = "0"
# SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[servers."os/app-manager"]
LaunchAppBlocking = { id = 0, type = "blockingScalar", approval = "autoAllow" }
SubscribeAppEvents = { id = 1, type = "archiveEvent", approval = "autoAllow" }
LaunchApp = { id = 2, type = "scalar", approval = "autoAllow" }
GetAppName = { id = 3, type = "blockingArchive", permissionGroup = "app-management.app-metadata", approval = "autoAllow" }
GetQrMatchRules = { id = 4, type = "blockingArchive", permissionGroup = "app-management.app-metadata", approval = "autoAllow" }
ListApps = { id = 5, type = "blockingArchive", approval = "autoAllow" }
GetThirdPartyCertificates = { id = 6, type = "blockingArchive", approval = "autoAllow" }
ImportThirdPartyCertificate = { id = 7, type = "blockingArchive", approval = "autoAllow" }
RemoveThirdPartyCertificate = { id = 8, type = "blockingArchive", approval = "autoAllow" }
GetAppIcon = { id = 9, type = "blockingArchive", permissionGroup = "app-management.app-metadata", approval = "autoAllow" }
RefreshInstalledApps = { id = 11, type = "blockingScalar" }
RemoveInstalledApp = { id = 12, type = "blockingArchive", approval = "autoAllow" }
SetAppPermissionGrant = { id = 14, type = "blockingArchive", approval = "autoAllow" }
GetPermissionRequestInfo = { id = 15, type = "blockingArchive" }
