// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size } from "@ui/theme.slint";
import { NavHeader, MenuBooleanItem, MenuSection, MenuSectionLayout, HLine, BasePage, PageBody, MenuActionItem, ContentSection } from "@ui/widgets.slint";
import { Navigate } from "../../gen/navigate.slint";
import { Callbacks, Global } from "../../globals.slint";
import { SettingsProps } from "./props.slint";
import { MenuSectionContainer } from "../../../../../ui/ui/widgets.slint";

export component SettingsPage inherits BasePage {
    in property <SettingsProps> props;

    VerticalLayout {
        NavHeader {
            title: @tr("Legacy Settings");
            clicked => {
                Navigate.backward();
            }
        }

        PageBody {
            ContentSection {
                VerticalLayout {
                    spacing: Size.sz4;

                    if (Global.seed-configured): MenuSection {
                        title: "Seed Management";

                        MenuSectionLayout {
                            MenuActionItem {
                                first: true;
                                label: "View current Seed"; // TODO: i18n
                                clicked => {
                                    Navigate.view-seed-words({ });
                                }
                            }

                            HLine { }

                            MenuActionItem {
                                last: true;
                                label: "Remove current Seed"; // TODO: i18n
                                clicked => {
                                    Navigate.seed-delete-quiz({ });
                                }
                            }
                        }
                    }

                    MenuSection {
                        title: "App Selection";
                        MenuSectionLayout {
                            for entry[index] in Global.all-apps: VerticalLayout {
                                if (index > 0): HLine { }
                                MenuBooleanItem {
                                    label: entry.name;
                                    checked: entry.enabled;
                                    changed(checked) => {
                                        Callbacks.app-toggled(entry.app-id, checked);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
