// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size } from "@ui/theme.slint";
import { Button, NavHeader, Icon, HeadingLg, TextMd, JumboIconPageBody, WrappedIcon, ButtonSection, ContentSection } from "@ui/widgets.slint";
import { Navigate, Animate } from "../../gen/navigate.slint";
import { Callbacks } from "../../globals.slint";
import { SeedDeleteProps } from "./props.slint";

export component SeedDeletePage inherits JumboIconPageBody {
    in property <SeedDeleteProps> props;

    ContentSection {
        HorizontalLayout {
            alignment: center;

            WrappedIcon {
                name: "jumbo-circle";
                inner-icon: "check";
            }
        }

        HeadingLg {
            text: "Seed Deleted Successfully"; // TODO: i18n
            horizontal-alignment: center;
        }
    }

    ButtonSection {
        Button {
            label: "Continue";
            importance: primary;
            clicked => {
                Navigate.intro({ replace: true });
            }
        }
    }
}
