// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

@rust-attr(route(path = "/trusted-publisher-details?{name}&{company}&{contact_email}&{support_url}&{public_key}&{serial_number}&{subject}&{basic_constraints}&{key_usage}&{extended_key_usage}"))
export struct TrustedPublisherDetailsProps {
    name: string,
    company: string,
    contact_email: string,
    support_url: string,
    public_key: string,
    serial_number: string,
    subject: string,
    basic_constraints: string,
    key_usage: string,
    extended_key_usage: string,
}
