# SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[servers."os/gui-app-emu-flux"]
SvcCall = { id = 0, type = "blockingScalar" }
SendSeph = { id = 1, type = "archive" }
RecvSeph = { id = 2, type = "blockingArchive" }
SyscallBuffer = { id = 3, type = "lendMut" }
