// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Theme-editor build script.
//!
//! Today this does two things:
//!   1. Compiles the Slint UI (`ui/app.slint`) with the `@components` import alias mapped to
//!      `../components/ui`.
//!   2. Scans `defaults/components/*.schema.json` and emits a generated `OUT_DIR/components_generated.rs`
//!      containing the list of built-in component specs the loader uses. The hand-written
//!      `BUILTIN_COMPONENTS` array is asserted against this list at runtime so a forgotten component schema
//!      or a new component file with no schema fails CI rather than silently disappearing from the preview.
//!
//! This is the scaffolding for H15 (generating the entire `preview.slint`
//! from plugin metadata). Generating the 5500-line file in one go is a
//! follow-up; metadata-derived parts can migrate in piecemeal.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let components_dir = manifest_dir.join("defaults").join("components");

    emit_component_metadata(&components_dir).expect("failed to emit component metadata");

    println!("cargo:rerun-if-changed=defaults/components");

    let config = slint_build::CompilerConfiguration::new().with_style("native".into()).with_library_paths(
        std::collections::HashMap::from([
            ("components".into(), std::path::PathBuf::from("../components/ui")),
            // The editor renders with the shared, no-overrides component themes;
            // apps get a per-app `@theme` dir generated by `foundation build`.
            ("theme".into(), std::path::PathBuf::from("../components/ui")),
        ]),
    );

    slint_build::compile_with_config("ui/app.slint", config).unwrap();
}

fn emit_component_metadata(components_dir: &Path) -> std::io::Result<()> {
    let mut entries: BTreeMap<String, (String, String)> = BTreeMap::new();

    if components_dir.is_dir() {
        for entry in fs::read_dir(components_dir)? {
            let entry = entry?;
            let path = entry.path();
            let file_name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            let Some(key) = file_name.strip_suffix(".schema.json") else {
                continue;
            };
            let key = key.to_string();
            if key.is_empty() {
                continue;
            }
            let content = fs::read_to_string(&path)?;
            let value: serde_json::Value = match serde_json::from_str(&content) {
                Ok(v) => v,
                Err(e) => {
                    println!("cargo:warning=skipping invalid component schema {}: {e}", path.display());
                    continue;
                }
            };
            let component = value.get("component").and_then(|v| v.as_str()).unwrap_or("").to_string();
            let source_file = value
                .get("source_file")
                .and_then(|v| v.as_str())
                .map(str::to_string)
                .unwrap_or_else(|| format!("{key}.slint"));
            if component.is_empty() {
                println!(
                    "cargo:warning=component schema {} has no top-level 'component' name; skipping",
                    path.display()
                );
                continue;
            }
            entries.insert(key, (component, source_file));
        }
    }

    let mut out = String::from(
        "// AUTOGENERATED by build.rs from defaults/components/*.schema.json — do not edit by hand.\n\
         pub(crate) const GENERATED_BUILTIN_COMPONENTS: &[(&str, &str, &str)] = &[\n",
    );
    for (key, (component, source_file)) in &entries {
        out.push_str(&format!(
            "    ({key:?}, {component:?}, {source:?}),\n",
            key = key,
            component = component,
            source = source_file,
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("components_generated.rs"), out)?;
    Ok(())
}
