// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

mod animation;
mod auto_lock;
mod blur;
#[cfg(not(feature = "recovery-os"))]
mod camera;
mod capture;
mod close;
mod control_center;
mod display;
mod framebuffer;
#[cfg(keyos)]
mod gpio;
mod handlers;
mod keyboard;
mod layers;
mod modal;
mod navigation;
#[cfg(not(feature = "recovery-os"))]
mod permissions;
mod pwrbutton;
mod registry;
mod rgbled;
mod switcher;
mod touch;
mod virtbutton;

// Generated by build.rs from `os/gui-server/i18n/*.json` (registered in localizer.json): provides
// `tr::TrId` and `tr::lookup_id` for the permission prompt strings, with no Slint dependency.
include!(concat!(env!("OUT_DIR"), "/tr.rs"));

#[cfg(not(feature = "recovery-os"))]
use std::collections::VecDeque;

use {
    crate::{
        animation::{BacklightAnimation, SwitchingAnimation},
        control_center::ControlCenterWindow,
        display::PlatformDisplay,
        framebuffer::BufferChain,
        handlers::*,
        keyboard::{KeyboardState, KeyboardWindow},
        modal::ModalState,
        pwrbutton::PowerButtonState,
        registry::{AppRegistry, AppRole},
        rgbled::RgbLedState,
        touch::TouchState,
    },
    animation::{AnimationCompleteAction, NextFrameAnimationState, ProgressControl},
    auto_lock::AutoLockState,
    blur::{BlurBufferState, BlurThread},
    gui_server_api::{
        consts::{CONTROL_CENTER_HEIGHT_EXPANDED_PX, DEFAULT_KEYBOARD_HEIGHT, SCREEN_HEIGHT, SCREEN_WIDTH},
        msg::*,
        AppName, ControlCenterColor, GuiServerError, InputMessage, RegisterApp,
    },
    log::{debug, error, warn},
    server::{ArchiveRequest, MessageId as _, Server, ServerContext},
    std::{
        collections::HashMap,
        time::{Duration, Instant},
    },
    xous::{MemoryFlags, MemoryRange, SystemEvent, CID, PID},
    xous_ticktimer::{Ticktimer, TicktimerCallback},
};

app_manager::use_api!();
#[cfg(not(feature = "recovery-os"))]
fs::use_api!();
haptics::use_api!();
power_manager::use_api!();
power_manager::use_ext_api!();
#[cfg(not(feature = "recovery-os"))]
security::use_api!();
#[cfg(not(feature = "recovery-os"))]
settings::use_api!();
#[cfg(not(feature = "recovery-os"))]
bt::use_api!();

const HAPTICS_CONNECTION_TIMEOUT_MS: u64 = 1000;

#[cfg(all(keyos, not(feature = "recovery-os")))]
const SHUTTING_DOWN_BITMAP_H: usize = 23;
#[cfg(all(keyos, not(feature = "recovery-os")))]
const SHUTTING_DOWN_BITMAP_W: usize = 224;
#[cfg(all(keyos, not(feature = "recovery-os")))]
const SHUTTING_DOWN_BITMAP: &[u8; SHUTTING_DOWN_BITMAP_H * SHUTTING_DOWN_BITMAP_W] =
    include_bytes!("../assets/shutting_down.raw");

#[cfg(all(keyos, not(feature = "recovery-os")))]
const REBOOTING_BITMAP_H: usize = 23;
#[cfg(all(keyos, not(feature = "recovery-os")))]
const REBOOTING_BITMAP_W: usize = 167;
#[cfg(all(keyos, not(feature = "recovery-os")))]
const REBOOTING_BITMAP: &[u8; REBOOTING_BITMAP_H * REBOOTING_BITMAP_W] =
    include_bytes!("../assets/rebooting.raw");

#[derive(Debug)]
pub struct AppWindow {
    name: AppName,
    control_center_color: Option<ControlCenterColor>,
    close_state: AppCloseState,
    last_active: Instant,
    input_cid: CID,
    buffers: BufferChain,
    blur_state: BlurBufferState,
    keyboard_state: KeyboardState,
    kiosk_policy: KioskPolicy,
    #[cfg(not(feature = "recovery-os"))]
    camera_state: crate::camera::CameraState,
    notified_shown: bool,
}

impl Drop for AppWindow {
    fn drop(&mut self) {
        if let Err(err) = xous::disconnect(self.input_cid) {
            log::error!("failed to disconnect input CID {:?} for {:?}: {:?}", self.input_cid, self.name, err);
        }
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
struct KioskPolicy {
    home_button_enabled: bool,
    power_button_enabled: bool,
    control_center_enabled: bool,
    auto_lock_enabled: bool,
}

impl Default for KioskPolicy {
    fn default() -> Self {
        Self {
            home_button_enabled: true,
            power_button_enabled: true,
            control_center_enabled: true,
            auto_lock_enabled: true,
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) enum AppCloseState {
    /// Registered
    Running,
    /// CloseRequested sent to the app, waiting for it to close
    Closing,
    /// Closing state timed out, terminate_process called on it.
    Terminating,
}
#[derive(Debug)]
pub(crate) enum GuiState {
    Splash,
    SplashFade {
        to: PID,
        progress: usize,
    },

    /// The current window is being displayed.
    SingleWindow {
        pid: PID,
        next_frame_animation: NextFrameAnimationState,
        navigation_request: Option<ArchiveRequest<NavigateTo>>,
    },
    Switching {
        from: PID,
        to: PID,
        progress: usize,
        animation: SwitchingAnimation,
        navigation_request: Option<ArchiveRequest<NavigateTo>>,
    },

    /// Displaying one app on top of the other (as a modal)
    Modal(ModalState),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum StartupState {
    // Only constructed on device builds of the full OS; recovery and hosted
    // builds boot straight to WaitingForLauncherPID.
    #[cfg_attr(any(feature = "recovery-os", not(keyos)), allow(dead_code))]
    InitialLockScreen,
    #[cfg_attr(any(feature = "recovery-os", not(keyos)), allow(dead_code))]
    WaitingForOnboardingPID,
    WaitingForLauncherPID,
    Started,
}

#[derive(server::Server)]
#[name = "os/gui-server"]
pub struct Gui {
    sid: Option<xous::SID>,
    windows: HashMap<PID, AppWindow>,

    app_registry: AppRegistry,

    waiting_for_pid: Option<(PID, Option<ArchiveRequest<NavigateTo>>)>,
    notified_nav_request: Option<(PID, Vec<u8>)>,
    /// Kernel ids of parked permission requests waiting for a display slot; each is re-resolved
    /// against the grant state when it is popped for display.
    #[cfg(not(feature = "recovery-os"))]
    pending_permission_requests: VecDeque<u16>,
    #[cfg(not(feature = "recovery-os"))]
    app_manager: AppManagerApi,
    #[cfg(not(keyos))]
    pending_restore_name: Option<String>,

    control_center_window: Option<ControlCenterWindow>,
    keyboard_window: Option<KeyboardWindow>,

    #[cfg(not(feature = "recovery-os"))]
    camera_window: crate::camera::CameraWindow,

    display: PlatformDisplay,
    layers: crate::layers::LayerStack,
    last_vsync_time: u64,
    ticktimer: Ticktimer,

    state: GuiState,
    animation_fb: MemoryRange,
    touch_state: TouchState,
    rgb_led: RgbLedState,
    power_button_state: PowerButtonState,
    auto_lock: AutoLockState,
    close_app_callback: Option<TicktimerCallback>,
    shutting_down: Option<bool>,
    blur_thread: BlurThread,
    backlight_animation: Option<BacklightAnimation>,

    #[cfg(not(feature = "recovery-os"))]
    security: Security,
    #[cfg(not(feature = "recovery-os"))]
    settings: SettingsApi,
    /// The device locale, seeded and kept fresh by a settings subscription so the permission
    /// prompt need not fetch it over IPC on every prompt.
    #[cfg(not(feature = "recovery-os"))]
    locale: settings::global::Locale,
    #[cfg(all(keyos, not(feature = "recovery-os")))]
    developer_mode_enabled: bool,
    startup_state: StartupState,
}

impl Server for Gui {
    fn on_start(&mut self, context: &mut ServerContext<Self>) {
        self.sid = Some(context.sid());

        xous::register_system_event_handler(
            SystemEvent::Disconnected,
            context.sid(),
            DisconnectHandlerMessage::ID,
        )
        .expect("register children crash handler");

        xous::register_system_event_handler(
            SystemEvent::LowFreeMemory,
            context.sid(),
            OnFreeMemoryBelowThreshold::ID,
        )
        .expect("register free memory alert handler");

        // The recovery image has no app manager to resolve prompts, so the permission broker
        // is compiled out there and never subscribes.
        #[cfg(not(feature = "recovery-os"))]
        xous::register_system_event_handler(
            SystemEvent::PermissionRequest,
            context.sid(),
            PermissionRequest::ID,
        )
        .expect("register permission request handler");

        #[cfg(keyos)]
        self.subscribe_to_gpio(context);

        self.power_button_state.init(context.sid()).expect("Failed to initialize timer state");

        #[cfg(not(feature = "recovery-os"))]
        {
            #[cfg(keyos)]
            {
                self.settings.server_subscribe_developer_mode(context);
            }
            self.settings.server_subscribe_screen_brightness(context);
            self.settings.server_subscribe_touch_offset(context);
            self.settings.server_subscribe_onboarding_status(context);
            // Delivers the current locale immediately, then on every change, into `self.locale`.
            self.settings.server_subscribe_locale(context);
            FileSystem::default().subscribe_filesystem_events(context, fs::Location::AppData);
        }

        #[cfg(not(feature = "recovery-os"))]
        {
            if let Err(error) = self.camera_window.api.subscribe(context) {
                log::warn!("Failed to subscribe to camera frames: {error:?}");
            }
        }

        self.init_auto_lock(context);

        #[cfg(not(keyos))]
        self.rgb_led.subscribe_color_updates(context);

        self.display.subscribe_to_vsync(context);

        self.close_app_callback =
            Some(TicktimerCallback::new(context.sid()).expect("Cannot register close app callback"));

        self.blur_thread.start(context.sid());

        #[cfg(not(keyos))]
        let _ = context;
    }
}

impl Gui {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Result<Self, GuiServerError> {
        let display = PlatformDisplay::init(Self::boot_splash_layer());
        #[cfg(not(feature = "recovery-os"))]
        let security = security::Security::default();
        #[cfg(all(not(feature = "recovery-os"), keyos))]
        let startup_state = if let security::MasterKeyState::Normal = security.master_key_state() {
            StartupState::InitialLockScreen
        } else {
            Self::launch_onboarding();
            StartupState::WaitingForOnboardingPID
        };
        #[cfg(any(feature = "recovery-os", all(not(feature = "recovery-os"), not(keyos))))]
        let startup_state = StartupState::WaitingForLauncherPID;

        let animation_fb = xous::map_memory(
            None,
            None,
            SCREEN_HEIGHT * SCREEN_WIDTH * 4,
            MemoryFlags::W | MemoryFlags::POPULATE | MemoryFlags::PLAINTEXT,
        )
        .expect("Could not allocate animation buffer");

        Ok(Gui {
            sid: None,
            state: GuiState::Splash,
            windows: HashMap::new(),
            app_registry: Default::default(),
            keyboard_window: None,
            control_center_window: None,
            #[cfg(not(feature = "recovery-os"))]
            camera_window: Default::default(),
            waiting_for_pid: None,
            notified_nav_request: None,
            #[cfg(not(feature = "recovery-os"))]
            pending_permission_requests: VecDeque::new(),
            #[cfg(not(feature = "recovery-os"))]
            app_manager: AppManagerApi::default(),
            #[cfg(not(keyos))]
            pending_restore_name: None,
            animation_fb,

            display,
            layers: Default::default(),
            last_vsync_time: 0,
            ticktimer: Ticktimer::default(),

            touch_state: TouchState::init(),
            rgb_led: RgbLedState::default(),
            power_button_state: PowerButtonState::default(),
            auto_lock: AutoLockState::default(),
            close_app_callback: None,
            shutting_down: None,
            blur_thread: BlurThread::default(),
            backlight_animation: None,

            #[cfg(not(feature = "recovery-os"))]
            security,
            #[cfg(not(feature = "recovery-os"))]
            settings: SettingsApi::default(),
            #[cfg(not(feature = "recovery-os"))]
            locale: settings::global::Locale::default(),
            #[cfg(all(keyos, not(feature = "recovery-os")))]
            developer_mode_enabled: cfg!(not(feature = "production")),
            startup_state,
        })
    }

    pub fn with_active_app<F, R>(&self, f: F) -> Option<R>
    where
        F: FnOnce(&AppWindow) -> R,
    {
        if let Some(current_app) = self.active_app_pid().and_then(|pid| self.windows.get(&pid)) {
            return Some(f(current_app));
        }

        None
    }

    pub fn with_active_app_mut<F, R>(&mut self, f: F) -> Option<R>
    where
        F: FnOnce(&mut AppWindow) -> R,
    {
        if let Some(current_app) = self.active_app_pid().and_then(|pid| self.windows.get_mut(&pid)) {
            return Some(f(current_app));
        }

        None
    }

    fn handle_register_app(&mut self, pid: PID, msg: RegisterApp) -> Result<(), GuiServerError> {
        if msg.height != SCREEN_HEIGHT {
            log::error!("App tried to register with invalid height: {} != {}", msg.height, SCREEN_HEIGHT);
            return Err(GuiServerError::InternalError);
        }
        match (self.app_registry.role(pid), self.startup_state) {
            (Some(AppRole::Launcher), StartupState::WaitingForLauncherPID)
            | (Some(AppRole::Onboarding), StartupState::WaitingForOnboardingPID) => {
                self.waiting_for_pid = Some((pid, None));
                self.startup_state = StartupState::Started;
            }
            (Some(AppRole::LockScreen), StartupState::InitialLockScreen) => {
                self.waiting_for_pid = Some((pid, None));
            }
            _ => {}
        }
        self.windows.insert(
            pid,
            AppWindow {
                name: msg.name.clone(),
                control_center_color: None,
                close_state: AppCloseState::Running,
                last_active: Instant::now(),
                blur_state: BlurBufferState::default(),
                keyboard_state: KeyboardState::default(),
                kiosk_policy: KioskPolicy::default(),
                #[cfg(not(feature = "recovery-os"))]
                camera_state: crate::camera::CameraState::default(),
                input_cid: msg.cid,
                buffers: BufferChain::new(msg.cid, u16::try_from(SCREEN_HEIGHT).unwrap(), pid),
                notified_shown: false,
            },
        );
        let name = msg.name.clone();
        self.notify_switcher_app_started(pid, &name);
        self.update_window_visibility();
        self.update_navigation_request_state();

        // If this app was the active window before it disconnected (e.g. hot-reload),
        // switch back to it once it submits its first frame.
        #[cfg(not(keyos))]
        if self.pending_restore_name.as_deref() == Some(&name) && self.waiting_for_pid.is_none() {
            self.pending_restore_name = None;
            self.waiting_for_pid = Some((pid, None));
        }

        debug!("Returning success");
        Ok(())
    }

    fn handle_register_control_center_app(
        &mut self,
        pid: PID,
        cid: CID,
        height: usize,
    ) -> Result<(), GuiServerError> {
        if height != CONTROL_CENTER_HEIGHT_EXPANDED_PX {
            log::error!(
                "Control Center tried to register with invalid height: {} != {}",
                height,
                CONTROL_CENTER_HEIGHT_EXPANDED_PX
            );
            return Err(GuiServerError::InternalError);
        }
        self.control_center_window = Some(ControlCenterWindow::new(cid, pid)?);
        self.notify_control_center_color();
        Ok(())
    }

    fn handle_register_keyboard_app(
        &mut self,
        pid: PID,
        cid: CID,
        height: usize,
    ) -> Result<(), GuiServerError> {
        if height != DEFAULT_KEYBOARD_HEIGHT {
            log::error!(
                "Keyboard tried to register with invalid height: {} != {}",
                height,
                DEFAULT_KEYBOARD_HEIGHT
            );
            return Err(GuiServerError::InternalError);
        }
        self.keyboard_window = Some(KeyboardWindow {
            input_cid: cid,
            pid,
            buffers: BufferChain::new(cid, u16::try_from(DEFAULT_KEYBOARD_HEIGHT).unwrap(), pid),
            blur_state: BlurBufferState::default(),
            last_update_args: Vec::new(),
            last_drawn_args: Vec::new(),
            notified_shown: false,
        });

        Ok(())
    }

    fn switch_to_launcher(&mut self) {
        if let Some(launcher_app_pid) = self.app_registry.pid(AppRole::Launcher) {
            let launcher_already_active = self.active_app_pid() == Some(launcher_app_pid);
            match &mut self.state {
                // Special case: we are already displaying the launcher, but it's in a modal state:
                GuiState::Modal(modal_state) if modal_state.background_pid() == launcher_app_pid => {
                    modal_state.respond(Err(gui_server_api::error::NavigationError::CanceledBySystem));
                }
                _ if launcher_already_active => {
                    self.notify_launcher_clear_rearrange_state();
                }
                _ => self.switch_to_window(launcher_app_pid),
            }
        } else {
            warn!("Tried to switch to launcher while no launcher is registered");
        }
    }

    fn notify_launcher_clear_rearrange_state(&self) {
        let Some(launcher_app_pid) = self.app_registry.pid(AppRole::Launcher) else {
            return;
        };
        if let Some(window) = self.windows.get(&launcher_app_pid) {
            // Custom1 asks the launcher to leave rearrange mode.
            if let Err(e) = xous::send_message(
                window.input_cid,
                xous::Message::new_scalar(InputMessage::Custom1 as usize, 0, 0, 0, 0),
            ) {
                error!("Failed to notify launcher to clear rearrange state: {e:?}");
            }
        }
    }

    #[cfg(not(feature = "recovery-os"))]
    fn notify_launcher_clear_transient_state(&self) {
        let Some(launcher_app_pid) = self.app_registry.pid(AppRole::Launcher) else {
            return;
        };
        if let Some(window) = self.windows.get(&launcher_app_pid) {
            // Custom2 asks the launcher to clear lock-sensitive transient state.
            if let Err(e) = xous::send_message(
                window.input_cid,
                xous::Message::new_scalar(InputMessage::Custom2 as usize, 0, 0, 0, 0),
            ) {
                error!("Failed to notify launcher to clear transient state: {e:?}");
            }
        }
    }

    fn switch_to_app_switcher(&mut self) {
        if let Some(switcher_app_pid) = self.app_registry.pid(AppRole::Switcher) {
            self.switch_to_window(switcher_app_pid);
        } else {
            warn!("Tried to switch to switcher while no switcher is registered");
        }
    }

    fn handle_submit_frame(&mut self, frame: SubmitFrame, pid: xous::PID) {
        if let Some(window) = &mut self.control_center_window
            && window.pid == pid
        {
            if !window.buffers.buffer_received(pid, frame.buffer) {
                return;
            }
        } else if let Some(window) = &mut self.keyboard_window
            && window.pid == pid
        {
            if !window.buffers.buffer_received(pid, frame.buffer) {
                return;
            }
            // We finally got a frame matching the latest payload, let the
            // slide-in animation proceed.
            if window.last_drawn_args != window.last_update_args {
                window.last_drawn_args = window.last_update_args.clone();
                self.keyboard_animation_tick();
            }
        } else {
            self.handle_app_frame(pid, frame)
        };
        self.update_layers();
    }

    fn handle_app_frame(&mut self, pid: PID, frame: SubmitFrame) {
        let Some(window) = self.windows.get(&pid) else {
            log::error!("SubmitFrame coming from an unknown PID {pid:?}");
            xous::unmap_memory(frame.buffer).ok();
            return;
        };

        let previous_buffer = window.buffers.most_recent_buffer();
        let expected_len = window.buffers.required_framebuffer_len();

        let window = self.windows.get_mut(&pid).unwrap();
        if !window.buffers.buffer_received(pid, frame.buffer) {
            return;
        }
        window.blur_state.mark_stale();

        match &mut self.state {
            GuiState::Modal(modal_state) if modal_state.modal_pid() == pid && modal_state.is_waiting() => {
                modal_state.expand();
            }

            GuiState::SingleWindow { pid: current_pid, next_frame_animation, .. } if *current_pid == pid => {
                if let NextFrameAnimationState::Waiting { kind } = next_frame_animation
                    && let Some(previous_buffer) = previous_buffer
                {
                    if previous_buffer.len() == expected_len && self.animation_fb.len() == expected_len {
                        self.animation_fb.as_slice_mut::<u32>().copy_from_slice(previous_buffer.as_slice());
                        #[cfg(keyos)]
                        xous::flush_cache(self.animation_fb, xous::CacheOperation::Clean).ok();

                        *next_frame_animation =
                            NextFrameAnimationState::Animating { progress: 0, kind: *kind };
                    } else {
                        log::error!(
                            "Skipping next-frame animation for PID={pid:?}: framebuffer length mismatch"
                        );
                        *next_frame_animation = NextFrameAnimationState::NotAnimating;
                    }
                }
            }
            _ => {}
        }

        if let Some((wait_pid, nav)) = &mut self.waiting_for_pid {
            if *wait_pid == pid {
                let nav = core::mem::take(nav);
                self.switch_to_window_with_nav(pid, nav);
                self.notify_switcher_update_app_fb(pid);
                self.waiting_for_pid = None;
            }
        }
    }

    fn on_vsync(&mut self) {
        self.update_vsync_states();
        self.keyboard_animation_tick();
        self.state_animation_tick();
        self.control_center_animation_tick();
        self.backlight_animation_tick();
        self.blur_vsync();
        self.update_layers();
        self.switcher_timeout_tick();
    }

    // Vsync interrupts can come any time, and the on_vsync handler might run after other
    // frame submission or request handlers due to queueing.
    // Calling this makes sure we have the most up-to-date buffer states available for
    // those handlers.
    pub fn update_vsync_states(&mut self) {
        if PlatformDisplay::vsync_happened() {
            // The +7ms is to account for inaccuracies and the fact that the interrupt
            // is sent a before rendering starts (in the vertical blanking interval)
            self.last_vsync_time = self.ticktimer.elapsed_ms() + 7;
            self.vsync_framebuffers();
        }
    }

    fn switch_to_window(&mut self, pid: PID) { self.switch_to_window_with_nav(pid, None); }

    fn switch_to_window_with_nav(
        &mut self,
        pid: PID,
        navigation_request: Option<ArchiveRequest<NavigateTo>>,
    ) {
        let Some(window) = self.windows.get_mut(&pid) else {
            self.waiting_for_pid = Some((pid, navigation_request));
            return;
        };

        // Clear any pending nav requests, since the new one will
        // replace it. This will unblock any apps waiting on the
        // stale request, which may not be completed if the user
        // has navigated away from it.
        match &mut self.state {
            GuiState::SingleWindow { navigation_request: stale_nav_request, .. } => {
                stale_nav_request.take();
            }
            GuiState::Switching { navigation_request: stale_nav_request, .. } => {
                stale_nav_request.take();
            }
            _ => {}
        }

        if window.buffers.most_recent_buffer().is_none() {
            self.waiting_for_pid = Some((pid, navigation_request));
            self.update_window_visibility();
            return;
        }
        if window.close_state != AppCloseState::Running {
            log::error!("Trying to switch to closing app pid={pid}");
            return;
        }
        let Some(from) = self.switch_source_pid() else {
            log::info!("Switching to initial window, PID={pid}");
            self.rgb_led.turn_on();
            self.change_state(GuiState::SplashFade { to: pid, progress: 0 });
            self.reset_auto_lock();
            return;
        };
        if pid == from {
            if navigation_request.is_some() {
                self.change_state(GuiState::SingleWindow {
                    pid,
                    next_frame_animation: NextFrameAnimationState::NotAnimating,
                    navigation_request,
                });
            }
        } else {
            let animation = self.switching_animation(from, pid);
            self.change_state(GuiState::Switching {
                from,
                to: pid,
                progress: 0,
                animation,
                navigation_request,
            });
        }
    }

    fn send_visible_event(pid: PID, cid: CID) {
        if let Err(e) =
            xous::send_message(cid, xous::Message::new_scalar(InputMessage::Visible as usize, 0, 0, 0, 0))
        {
            error!("Failed to notify the app (PID {pid}) about being visible: {e:?}");
        }
    }

    fn send_hidden_event(pid: PID, cid: CID) {
        if let Err(e) =
            xous::send_message(cid, xous::Message::new_scalar(InputMessage::Hidden as usize, 0, 0, 0, 0))
        {
            error!("Failed to notify the app (PID {pid}) about being hidden: {e:?}");
        }
    }

    fn update_window_visibility(&mut self) {
        // Nothing is on screen with the display off, but keep the buffers so that turning
        // it back on shows the last frame right away.
        let lcd_on = self.display.is_lcd_on();

        let mut visible_pids = Vec::new();
        visible_pids.extend(self.active_app_pid());
        visible_pids.extend(self.waiting_for_pid.as_ref().map(|wfp| wfp.0));
        match &self.state {
            GuiState::Switching { from, .. } => visible_pids.push(*from),
            GuiState::Modal(modal_state) => {
                // Off screen once the modal covers it, except while the modal has no
                // window and `update_layers` still shows the background on its own.
                if modal_state.y() > 0 || !self.windows.contains_key(&modal_state.modal_pid()) {
                    visible_pids.push(modal_state.background_pid());
                }
            }
            GuiState::SplashFade { .. } | GuiState::SingleWindow { .. } | GuiState::Splash => {}
        }

        // Off screen, but kept framebuffer-backed so that whatever gets composited always
        // has pixels, and a switch to them does not have to wait for a first frame.
        let mut pids_that_need_buffers = Vec::new();
        pids_that_need_buffers.extend(self.modal_background_pid());
        pids_that_need_buffers.extend(self.app_registry.pid(AppRole::LockScreen));
        #[cfg(not(feature = "recovery-os"))]
        if self.is_locked() {
            pids_that_need_buffers
                .extend(self.app_registry.pre_lock_app_id().or(self.app_registry.pid(AppRole::Launcher)));
        }

        let mut update_switcher_fb_pids = Vec::new();

        for (pid, window) in &mut self.windows {
            let on_screen = visible_pids.contains(pid);
            let shown = lcd_on && on_screen;
            let buffers_kept = on_screen || pids_that_need_buffers.contains(pid);

            if shown != window.notified_shown {
                if shown {
                    Self::send_visible_event(*pid, window.input_cid);
                } else {
                    Self::send_hidden_event(*pid, window.input_cid);
                }
                window.notified_shown = shown;
            }

            if buffers_kept != window.buffers.is_shown() {
                if buffers_kept {
                    window.buffers.show();
                } else {
                    window.buffers.hide();
                    update_switcher_fb_pids.push(*pid);
                }
            }
        }

        for pid in update_switcher_fb_pids {
            self.notify_switcher_update_app_fb(pid);
        }
    }

    fn haptics_server_connection(&mut self) -> Option<HapticsApi> {
        HapticsApi::try_new_with_timeout(Duration::from_millis(HAPTICS_CONNECTION_TIMEOUT_MS))
    }

    pub(crate) fn haptics_click(&mut self) {
        if let Some(haptics) = self.haptics_server_connection() {
            haptics.click();
        }
    }

    pub(crate) fn haptics_triple_click(&mut self) {
        if let Some(haptics) = self.haptics_server_connection() {
            haptics.triple_click();
        }
    }

    pub(crate) fn shutdown(&mut self, reboot: bool) {
        self.shutting_down = Some(reboot);
        if let Some(active_app) = self.active_app_pid()
            && self.display.is_lcd_on()
        {
            #[cfg(all(keyos, not(feature = "recovery-os")))]
            if reboot {
                self.add_text_to_splash(REBOOTING_BITMAP_W, REBOOTING_BITMAP_H, REBOOTING_BITMAP);
            } else {
                self.add_text_to_splash(SHUTTING_DOWN_BITMAP_W, SHUTTING_DOWN_BITMAP_H, SHUTTING_DOWN_BITMAP);
            }
            self.change_state(GuiState::SplashFade { to: active_app, progress: 100 });
            self.touch_off();
        } else {
            self.close_all_apps();
        }
    }

    pub(crate) fn finalize_shutdown(&mut self) {
        #[cfg(not(feature = "recovery-os"))]
        self.settings.flush_settings();
        #[cfg(not(feature = "recovery-os"))]
        BluetoothApi::default().disconnect().ok();

        // Make sure the display is off before we reset to prevent the smearing glitch
        if self.display.is_lcd_on() {
            self.display.turn_lcd_off();
        }
        // XXX: Leave Some time for the last few logs to actually print
        std::thread::sleep(Duration::from_millis(50));

        let reboot = self.shutting_down.take().unwrap_or_default();
        if reboot {
            PowerManagerApi::default().reboot();
        } else {
            PowerManagerExtApi::default().shutdown();
        }
    }

    #[cfg(all(keyos, not(feature = "recovery-os")))]
    fn add_text_to_splash(&self, width: usize, height: usize, bitmap: &[u8]) {
        use gui_server_api::consts::{SCREEN_HEIGHT, SCREEN_WIDTH};
        let mut splash_range = unsafe {
            xous::MemoryRange::new(
                xous::keyos::BOOT_SPLASH_FB,
                xous::keyos::BOOT_SPLASH_PAGES * xous::keyos::PAGE_SIZE,
            )
            .unwrap()
        };
        let is_dark = self.settings.get_prime_color() == settings::global::SystemTheme::Dark;
        for y in 0..height {
            let y_offset = SCREEN_HEIGHT - 100;
            let x_offset = (SCREEN_WIDTH - width) / 2;
            for x in 0..width {
                for component in 0..3 {
                    let pixel_component = &mut splash_range.as_slice_mut::<u8>()
                        [((y + y_offset) * SCREEN_WIDTH + x + x_offset) * 4 + component];
                    if is_dark {
                        // Light text on dark bg
                        *pixel_component = pixel_component.saturating_add(bitmap[y * width + x]);
                    } else {
                        // Dark text on light bg
                        *pixel_component = pixel_component.saturating_sub(bitmap[y * width + x]);
                    }
                }
            }
        }
    }

    fn start_turning_off_lcd(&mut self) {
        self.rgb_led.turn_off();
        self.touch_off();
        self.animate_backlight_to(0, AnimationCompleteAction::LcdOff);
    }

    pub(crate) fn on_lcd_turned_off(&mut self) {
        if let Some(control_center) = &self.control_center_window {
            xous::send_message(
                control_center.input_cid,
                xous::Message::new_scalar(InputMessage::Hidden as usize, 0, 0, 0, 0),
            )
            .map_err(|e| error!("Failed to notify control center of LCD turning off: {e:?}"))
            .ok();
        }
        #[cfg(not(feature = "recovery-os"))]
        self.camera_window_notify_hidden();

        self.update_window_visibility();
    }

    fn turn_on_lcd(&mut self) {
        self.touch_on();
        self.animate_backlight_to(self.screen_brightness_setting(), AnimationCompleteAction::None);
        self.rgb_led.turn_on();
        self.display.turn_lcd_on();
        if let Some(control_center) = &self.control_center_window {
            // Control center is always visible as long as LCD is on
            xous::send_message(
                control_center.input_cid,
                xous::Message::new_scalar(InputMessage::Visible as usize, 0, 0, 0, 0),
            )
            .map_err(|e| error!("Failed to notify control center of LCD turning on: {e:?}"))
            .ok();
        }
        self.update_window_visibility();

        #[cfg(not(feature = "recovery-os"))]
        self.update_camera_window();
        self.update_layers();
    }

    /// Returns a PID of an active (focused) app window, if any.
    fn active_app_pid(&self) -> Option<PID> {
        match &self.state {
            GuiState::SingleWindow { pid, .. }
            | GuiState::Switching { to: pid, .. }
            | GuiState::SplashFade { to: pid, .. } => Some(*pid),
            GuiState::Modal(modal_state) => Some(modal_state.modal_pid()),
            GuiState::Splash => None,
        }
    }

    /// The special-app kind of the active window, if it is a registered special app.
    fn active_app_role(&self) -> Option<AppRole> {
        self.active_app_pid().and_then(|pid| self.app_registry.role(pid))
    }

    /// The window a switch moves away from, or `None` on the splash screen.
    fn switch_source_pid(&self) -> Option<PID> {
        match &self.state {
            // Switching dismisses the modal, so the window left behind is its background.
            GuiState::Modal(modal_state) => Some(modal_state.background_pid()),
            _ => self.active_app_pid(),
        }
    }

    pub(crate) fn is_onboarding_running(&self) -> bool {
        let onboarding_pid = self.app_registry.pid(AppRole::Onboarding);

        onboarding_pid.is_some()
            && (self.active_app_pid() == onboarding_pid || self.modal_background_pid() == onboarding_pid)
    }

    #[cfg(not(feature = "recovery-os"))]
    fn lock(&mut self) {
        let Some(lock_screen_pid) = self.app_registry.pid(AppRole::LockScreen) else {
            error!("No lock screen app PID found");
            return;
        };
        // When locked in a midst of opening an app, prefer `to` over `from`
        let current_app = match &self.state {
            GuiState::Switching { to, .. } => Some(*to),
            _ => self.modal_background_pid().or_else(|| self.active_app_pid()),
        };
        if current_app == self.app_registry.pid(AppRole::Onboarding) {
            debug!("Not locking during onboarding");
            return;
        }

        // If the switcher is focused during the locking, show the launcher after unlocking
        let pre_lock_app = if self.active_app_role() == Some(AppRole::Switcher) {
            self.app_registry.pre_lock_app_id().or_else(|| self.app_registry.pid(AppRole::Launcher))
        } else {
            current_app
        };

        if self.app_registry.pre_lock_app_id().is_none() && self.startup_state == StartupState::Started {
            self.app_registry.set_pre_lock_app_pid(pre_lock_app);
        }
        self.control_center_collapse();
        self.notify_launcher_clear_transient_state();
        self.security.log_out();
        self.switch_to_window(lock_screen_pid);
    }

    fn unlock(&mut self) {
        if self.startup_state != StartupState::Started {
            // This is the initial unlock. Wait for onboarding status.
            return;
        }
        let app_id = self.app_registry.pre_lock_app_id().or(self.app_registry.pid(AppRole::Launcher));
        self.app_registry.set_pre_lock_app_pid(None);
        if let Some(pid) = app_id {
            self.switch_to_window(pid);
        } else {
            error!("No launcher app PID found");
        }
    }

    fn is_locked(&self) -> bool { self.active_app_role() == Some(AppRole::LockScreen) }

    fn home_button_enabled(&self) -> bool { self.control_enabled(|policy| policy.home_button_enabled, false) }

    fn power_button_enabled(&self) -> bool {
        self.control_enabled(|policy| policy.power_button_enabled, true)
    }

    fn control_center_enabled(&self) -> bool {
        self.control_enabled(|policy| policy.control_center_enabled, true)
    }

    #[cfg(all(keyos, not(feature = "recovery-os")))]
    fn auto_lock_enabled(&self) -> bool { self.control_enabled(|policy| policy.auto_lock_enabled, true) }

    fn control_enabled(&self, enabled: fn(KioskPolicy) -> bool, active_default: bool) -> bool {
        let modal_allows = self.modal_background_pid().map_or(true, |pid| enabled(self.kiosk_policy(pid)));
        let active_allows =
            self.active_app_pid().map_or(active_default, |pid| enabled(self.kiosk_policy(pid)));

        modal_allows && active_allows
    }

    fn kiosk_policy(&self, pid: PID) -> KioskPolicy {
        self.windows.get(&pid).map(|window| window.kiosk_policy).unwrap_or_default()
    }

    #[cfg(not(feature = "recovery-os"))]
    pub fn launch_onboarding() {
        let app_already_running =
            xous::app_id_to_pid(&gui_server_api::navigation::ONBOARDING_APP_ID).unwrap_or_default().is_some();
        if !app_already_running {
            if let Err(e) =
                AppManagerApi::default().launch_app(&gui_server_api::navigation::ONBOARDING_APP_ID)
            {
                error!("Couldn't launch onboarding: {e:?}");
            }
        }
    }

    fn state_animation_tick(&mut self) {
        const SPLASH_TICK: usize = 6;
        const NEXT_FRAME_TICK: usize = 12;

        match &mut self.state {
            GuiState::Splash => (),
            GuiState::SingleWindow { next_frame_animation, .. } => {
                if let NextFrameAnimationState::Animating { progress, .. } = next_frame_animation {
                    if *progress < 100 - NEXT_FRAME_TICK {
                        *progress += NEXT_FRAME_TICK;
                    } else {
                        *next_frame_animation = NextFrameAnimationState::NotAnimating;
                    }
                }
            }
            GuiState::SplashFade { to, progress } => {
                if self.shutting_down.is_some() {
                    if *progress > SPLASH_TICK {
                        *progress -= SPLASH_TICK;
                    } else {
                        self.change_state(GuiState::Splash);
                        self.close_all_apps();
                    }
                } else {
                    if *progress < 100 - SPLASH_TICK {
                        *progress += SPLASH_TICK;
                    } else {
                        let pid = *to;
                        self.change_state_single_window(pid, None);
                    }
                }
            }
            GuiState::Switching { from, to, progress, navigation_request, animation, .. } => {
                let progress_step = animation.step_size_ticks();

                match animation {
                    SwitchingAnimation::ToSwitcher(ProgressControl::Abort) => {
                        if *progress >= progress_step {
                            *progress -= progress_step;
                        } else {
                            let pid = *from;
                            let _ = core::mem::take(navigation_request);
                            self.change_state_single_window(pid, None);
                        }
                    }

                    SwitchingAnimation::ToSwitcher(ProgressControl::Manual) => {}

                    _ => {
                        if *progress < 100 {
                            *progress = (*progress + progress_step).min(100);
                        } else {
                            let pid = *to;
                            let navigation_request = core::mem::take(navigation_request);
                            self.change_state_single_window(pid, navigation_request);
                        }
                    }
                }
            }
            GuiState::Modal(modal_state) => {
                let was_covered = modal_state.y() == 0;
                let collapsed = modal_state.animation_tick();
                let pid = modal_state.background_pid();
                let now_covered = modal_state.y() == 0;
                if collapsed {
                    // Modal was collapsed
                    self.change_state_single_window(pid, None);
                } else if now_covered != was_covered {
                    // Nothing else reruns this while the modal animates.
                    self.update_window_visibility();
                }
            }
        }
    }

    fn change_state_single_window(
        &mut self,
        pid: PID,
        navigation_request: Option<ArchiveRequest<NavigateTo>>,
    ) {
        if let Some(window) = self.windows.get_mut(&pid) {
            window.last_active = Instant::now();
            self.notify_switcher_app_activated(pid);
        } else {
            log::error!("Changing state to SingleWindow to a window that's not Active (pid={pid})");
        }
        self.change_state(GuiState::SingleWindow {
            pid,
            next_frame_animation: NextFrameAnimationState::NotAnimating,
            navigation_request,
        });
    }

    fn change_state(&mut self, new_state: GuiState) {
        log::debug!("Changing state to: {new_state:?}");

        self.state = new_state;
        self.notify_control_center_color();
        self.update_keyboard_window();
        #[cfg(not(feature = "recovery-os"))]
        self.update_camera_window();

        self.update_window_visibility();
        self.update_navigation_request_state();
        self.update_layers();

        // Any transition may have moved us into a state that can host a queued permission
        // prompt (a modal finished, or the device just unlocked); try to show the next one.
        // Showing it re-enters `change_state` with a modal state, where this is a no-op.
        #[cfg(not(feature = "recovery-os"))]
        self.show_next_permission_prompt();
    }
}

#[cfg(not(keyos))]
fn get_frame(entire_device: bool, mem: &mut xous::MemoryRange) {
    use gui_server_api::consts::{DEVICE_HEIGHT, DEVICE_WIDTH, SCREEN_HEIGHT, SCREEN_WIDTH};

    if entire_device {
        let mut image_buffer = image::ImageBuffer::from_raw(DEVICE_WIDTH, DEVICE_HEIGHT, mem.as_slice_mut())
            .expect("Screen grab buffer not big enough");
        display::draw::draw_whole_device(&mut image_buffer);
    } else {
        let mut image_buffer =
            image::ImageBuffer::from_raw(SCREEN_WIDTH as u32, SCREEN_HEIGHT as u32, mem.as_slice_mut())
                .expect("Screen grab buffer not big enough");
        display::draw::draw_lcd_contents(&mut image_buffer);
    };
}

#[cfg(keyos)]
fn main() {
    log_server::init_wait(env!("CARGO_CRATE_NAME")).unwrap();
    log::set_max_level(log::LevelFilter::Info);

    xous::set_thread_priority(xous::ThreadPriority::System3).unwrap();

    server::listen(Gui::new().expect("initialize gui server"))
}

#[cfg(not(keyos))]
fn main() {
    log_server::init_wait(env!("CARGO_CRATE_NAME")).unwrap();
    log::set_max_level(log::LevelFilter::Info);

    std::thread::Builder::new()
        .name("KeyOS GUI thread".to_string())
        .spawn(move || server::listen(Gui::new().expect("initialize gui server")))
        .expect("Spawn gui thread");

    display::window::run_window()
}
