// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { ManualBackupProps } from "props.slint";
import { Navigate } from "../../../gen/navigate.slint";
import {
    Dialog,
    ButtonSection,
    Button,
    HeadingMd,
    Link,
    NavHeader,
    TextMd,
    GlowShieldPage,
    ShieldSection,
    ShieldContent,
    OverlayImage,
} from "@ui/widgets.slint";
import { Importance, Palette, UISize } from "@ui/theme.slint";
import {
    BackupFlow,
    OnboardingCallbacks,
    SeedGlobal,
} from "../../../onboarding-callbacks.slint";
import { TR2, TrId } from "../../../gen/tr.slint";

export component ManualBackupPage inherits GlowShieldPage {
    in property <ManualBackupProps> props;

    property <bool> show-dialog:false;

    NavHeader {
        y: 0;
        clicked => {
            Navigate.backward();
        }

        if SeedGlobal.backup-flow == BackupFlow.RecoveredSeed
            || SeedGlobal.backup-flow == BackupFlow.NewDeviceKeycards: Link {
            label: TR2.lookup(TrId.CommonButtonSkip);
            importance: Importance.normal;
            clicked => {
                if SeedGlobal.backup-flow == BackupFlow.RecoveredSeed {
                    OnboardingCallbacks.set-magic-backup-enabled(false);
                }
                Navigate.connect-wallet({ });
            }
        }
    }

    ShieldSection {
        ShieldContent {
            HeadingMd {
                text: TR2.lookup(TrId.BackupManualMainHeader);
                horizontal-alignment: center;
            }

            TextMd {
                text: TR2.format(TrId.BackupManualMainSubheader, ["2", "3"]);
                color: Palette.content-secondary;
                horizontal-alignment: center;
            }
        }

        ButtonSection {
            Button {
                label: TR2.format(TrId.BackupManualMainXOfYKeycardBackup, ["2", "3"]);
                importance: primary;
                clicked => {
                    OnboardingCallbacks.set-magic-backup-enabled(false);
                    Navigate.manual-keycard-backup({ });
                }
            }

            Button {
                label: TR2.lookup(TrId.BackupManualMainViewSeedWords);
                importance: primary;
                clicked => {
                    show-dialog = true;
                }
            }
        }
    }

    OverlayImage {
        image: "images/three-d/manual-backup";
    }

    if show-dialog:Rectangle {
        background: Palette.overlay;

        Dialog {
            title: TR2.lookup(TrId.KeycardBackupManualModalBewareHeader);
            message: TR2.lookup(TrId.KeycardBackupManualModalBewareContent);
            ok-text: TR2.lookup(TrId.CommonButtonContinue);
            show-ok: true;
            cancel-text: TR2.lookup(TrId.CommonButtonCancel);
            show-cancel: true;
            show-close-button: true;
            width: UISize.modal-width;
            on-cancel => {
                show-dialog = false;
            }
            on-ok => {
                OnboardingCallbacks.set-magic-backup-enabled(false);
                Navigate.manual-backup-seed({ });
            }
        }
    }
}
