// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

@rust-attr(route(path = "/details?{app_id}&{icon_key}&{name}&{publisher}&{version}&{size}&{description}&{permissions}"))
export struct AppDetailsProps {
    app_id: string,
    icon_key: string,
    name: string,
    publisher: string,
    version: string,
    size: string,
    description: string,
    permissions: string,
}
