// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

use log::{debug, error, info};
use server::{
    ArchiveEventSubscriber, ArchiveEventSubscriptionHandler, BlockingArchiveHandler, BlockingScalar,
    BlockingScalarHandler, MessageId as _, ScalarHandler, Server, ServerContext,
};
use xous::{AppId, SystemEvent, PID};

mod install;
mod launch;
mod permission_catalog;
mod permission_grants;
mod registry;
mod system_messages;
mod third_party_certs;

// Generated by build.rs from `os/app-manager/i18n/*.json` (registered in localizer.json): provides
// `tr::TrId` and `tr::lookup_id_in` for the permission subgroup labels, resolved in the request's
// locale, with no Slint dependency.
include!(concat!(env!("OUT_DIR"), "/tr.rs"));

use std::cell::OnceCell;
use std::collections::{HashMap, HashSet};

use app_manager::{
    AppEvent, GetPermissionRequestInfo, GetThirdPartyCertificates, ImportThirdPartyCertificate,
    InstallAppArchive, InstallAppArchiveResult, InstallError, LaunchError, PermissionGrantDecision,
    PermissionRequestInfoResult, PreviewThirdPartyCertificate, RemoveInstalledAppResult,
    RemoveThirdPartyCertificate, RemoveThirdPartyCertificateResult, SetAppPermissionGrant,
    SetAppPermissionGrantResult, ThirdPartyCertificateError, ThirdPartyCertificateInfo,
};
use app_manager::{
    GetAppIcon, GetAppName, GetQrMatchRules, InstalledAppInfo, LaunchApp, LaunchAppBlocking, ListApps,
    RefreshInstalledApp, RefreshInstalledApps, RemoveApp, SubscribeAppEvents,
};
use fs::adapter::FsAdapter;
use permission_grants::PermissionGrantStore;
use semver::Version;
use system_messages::{ChildCrashed, Disconnected};
use third_party_certs::ThirdPartyCertificateStore;

crypto::use_api!();
fs::use_api!();
gui_server_api::use_api!();
security::use_api!();

#[cfg(not(keyos))]
use crate::launch::launch_app;
use crate::registry::AppRegistry;

pub fn listen() {
    #[cfg(not(keyos))]
    crate::launch::warn_if_app_elf_root_unset();
    server::listen(AppManagerServer::new().unwrap())
}

#[derive(server::Server)]
#[name = "os/app-manager"]
pub struct AppManagerServer {
    app_event_subscribers: Vec<ArchiveEventSubscriber<AppEvent>>,
    app_registry: AppRegistry,
    fs: FileSystem,
    permission_grants: PermissionGrantStore,
    /// Per-run "Not Now" answers, keyed by app id and permission subgroup. A subgroup here is
    /// auto-denied without re-prompting until the app relaunches, so a spammy or malicious app
    /// cannot loop the user on the same prompt (or walk through a subgroup's messages one by
    /// one). In-memory only; cleared when the app next launches.
    transient_permission_denies: HashMap<AppId, HashSet<String>>,
    third_party_cert_store: ThirdPartyCertificateStore,
    panic_message_buf: xous::MemoryRange,
    names: server::xous_names::XousNames,
    /// Connected on the first close request: connecting at startup would deadlock the boot,
    /// as gui-server waits for app-manager the same way.
    gui_server: OnceCell<GuiApiLight>,
    /// Apps whose removal waits for their process to finish closing; the removal resumes in
    /// the child-terminated handler.
    pending_close_removals: HashSet<AppId>,
}

impl Default for AppManagerServer {
    fn default() -> Self {
        let panic_message_buf =
            xous::map_memory(None, None, 0x1000, xous::MemoryFlags::W | xous::MemoryFlags::POPULATE)
                .expect("Failed to allocate panic message buffer");
        let fs = FileSystem::default();

        Self {
            app_event_subscribers: Vec::default(),
            app_registry: AppRegistry::new(running_keyos_version()),
            permission_grants: PermissionGrantStore::default(),
            transient_permission_denies: HashMap::new(),
            third_party_cert_store: ThirdPartyCertificateStore::new(fs.clone()),
            fs,
            panic_message_buf,
            names: server::xous_names::XousNames::new().expect("xous-names must be reachable"),
            gui_server: OnceCell::new(),
            pending_close_removals: HashSet::new(),
        }
    }
}

#[cfg(keyos)]
fn running_keyos_version() -> Version {
    let info = Security::default()
        .os_version_info()
        .expect("securam must return the running KeyOS version")
        .expect("securam must contain the running KeyOS version");
    let end = info.keyos_version.iter().position(|byte| *byte == 0).unwrap_or(info.keyos_version.len());
    let version = std::str::from_utf8(&info.keyos_version[..end])
        .expect("securam's running KeyOS version must be UTF-8");
    Version::parse(version.trim_start_matches('v'))
        .expect("securam's running KeyOS version must be valid SemVer")
}

#[cfg(not(keyos))]
fn running_keyos_version() -> Version {
    // Hosted builds do not receive the bootloader's KeyOS version argument.
    Version::new(u64::MAX, 0, 0)
}

impl BlockingArchiveHandler<GetQrMatchRules> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetQrMatchRules,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Vec<app_manager::AppQrMatchRules> {
        self.app_registry.qr_match_rules(&msg.app_ids, &self.third_party_cert_store.list())
    }
}

impl BlockingArchiveHandler<ListApps> for AppManagerServer {
    fn handle(
        &mut self,
        msg: ListApps,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Vec<InstalledAppInfo> {
        self.app_registry.list_apps(
            &msg.locale,
            &self.third_party_cert_store.list(),
            &msg.filter,
            &self.permission_grants,
        )
    }
}

impl BlockingScalarHandler<RefreshInstalledApps> for AppManagerServer {
    fn handle(
        &mut self,
        _msg: RefreshInstalledApps,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<(), app_manager::AppManagerError> {
        self.rescan_and_notify().map_err(|e| {
            error!("failed to refresh installed apps: {e:?}");
            app_manager::AppManagerError::InternalError
        })
    }
}

impl BlockingScalarHandler<RefreshInstalledApp> for AppManagerServer {
    fn handle(
        &mut self,
        RefreshInstalledApp(app_id): RefreshInstalledApp,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<(), app_manager::AppManagerError> {
        let mut diff = self.rescan_and_cache().map_err(|e| {
            error!("failed to refresh installed app 0x{}: {e:?}", hex::encode(app_id.0));
            app_manager::AppManagerError::InternalError
        })?;
        if !self.app_registry.is_sideloaded_app(app_id) {
            error!("refreshed sideloaded app 0x{} did not enter the registry", hex::encode(app_id.0));
            self.notify_app_set_changed(diff);
            return Err(app_manager::AppManagerError::InternalError);
        }
        diff.mark_installed(app_id);
        self.notify_app_set_changed(diff);
        Ok(())
    }
}

impl BlockingArchiveHandler<GetAppIcon> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetAppIcon,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Option<Vec<u8>> {
        let app_id = match app_manager::decode_app_id_str(&msg.app_id) {
            Ok(app_id) => app_id,
            Err(e) => {
                log::warn!("GetAppIcon: invalid app id {:?}: {e:?}", msg.app_id);
                return None;
            }
        };
        self.app_registry.app_icon_bytes(&self.fs, app_id, msg.variant)
    }
}

impl BlockingArchiveHandler<GetThirdPartyCertificates> for AppManagerServer {
    fn handle(
        &mut self,
        _msg: GetThirdPartyCertificates,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Vec<ThirdPartyCertificateInfo> {
        self.third_party_cert_store.list()
    }
}

impl BlockingArchiveHandler<PreviewThirdPartyCertificate> for AppManagerServer {
    fn handle(
        &mut self,
        msg: PreviewThirdPartyCertificate,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<ThirdPartyCertificateInfo, ThirdPartyCertificateError> {
        self.third_party_cert_store.preview(&msg.certificate_pem)
    }
}

impl BlockingArchiveHandler<ImportThirdPartyCertificate> for AppManagerServer {
    fn handle(
        &mut self,
        msg: ImportThirdPartyCertificate,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<ThirdPartyCertificateInfo, ThirdPartyCertificateError> {
        match self.third_party_cert_store.import(&msg.certificate_pem, &msg.expected_fingerprint) {
            Ok(cert) => {
                self.notify_allowed_publishers_changed();
                Ok(cert)
            }
            Err(error) => {
                if error.publisher_set_changed {
                    self.notify_allowed_publishers_changed();
                }
                Err(error.error)
            }
        }
    }
}

impl BlockingArchiveHandler<RemoveThirdPartyCertificate> for AppManagerServer {
    fn handle(
        &mut self,
        msg: RemoveThirdPartyCertificate,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> RemoveThirdPartyCertificateResult {
        // Only block removal while the certificate is still allowed. An expired cert can
        // no longer launch the app that was signed with it, so the user must be able to
        // delete the stale entry even though an installed app still references that key.
        if let Some(cert) = self.third_party_cert_store.allowed(&msg.fingerprint) {
            if let Some(app_name) =
                self.app_registry.app_name_requiring_third_party_key(&cert.public_key, &msg.locale)
            {
                return RemoveThirdPartyCertificateResult::AppRequiresKey(app_name);
            }
        }

        match self.third_party_cert_store.remove(&msg.fingerprint) {
            Ok(true) => {
                self.notify_allowed_publishers_changed();
                RemoveThirdPartyCertificateResult::Removed
            }
            Ok(false) => RemoveThirdPartyCertificateResult::NotFound,
            Err(e) => {
                error!("failed to remove third-party certificate: {e:?}");
                RemoveThirdPartyCertificateResult::InternalError
            }
        }
    }
}

impl ScalarHandler<RemoveApp> for AppManagerServer {
    fn handle(&mut self, RemoveApp(app_id): RemoveApp, sender: PID, _context: &mut ServerContext<Self>) {
        info!("PID {sender} is asynchronously removing app 0x{app_id}");
        self.remove_app(app_id);
    }
}

impl AppManagerServer {
    fn remove_app(&mut self, app_id: AppId) {
        self.notify_app_removing(app_id);

        // Flux children are installed and removed as apps of their own, so the emulator goes
        // last: removing it first would strand children nothing can run or remove.
        if self.app_registry.provides_flux_emulator(&app_id)
            && !self.app_registry.flux_child_app_ids().is_empty()
        {
            self.notify_removal_failed(app_id, RemoveInstalledAppResult::FluxAppsInstalled);
            return;
        }

        let Some(app_dir) = self.app_registry.removable_bundle_dir(app_id) else {
            if self.app_registry.contains_app(app_id) {
                self.notify_removal_failed(app_id, RemoveInstalledAppResult::NotSideloaded);
            } else {
                // The requested end state is already true. Still emit the successful terminal
                // event so asynchronous callers can clear removal UI and stale layout entries.
                let mut diff = registry::AppRegistryDiff::default();
                diff.mark_removed(app_id);
                self.notify_app_set_changed(diff);
            }
            return;
        };

        // A running app is gracefully closed first; the removal resumes in the
        // child-terminated handler.
        if let Some(pid) = self.app_registry.running_pid(&app_id) {
            info!("closing app 0x{app_id} (pid {pid}) before removing it");
            self.pending_close_removals.insert(app_id);
            let gui_server = self.gui_server.get_or_init(GuiApiLight::connect);
            if let Err(e) = gui_server.request_app_close(pid) {
                error!("failed to request closing app 0x{app_id} (pid {pid}): {e:?}");
            }
            return;
        }

        info!("removing app 0x{} from {app_dir}", hex::encode(app_id.0));

        match self.remove_app_bundle(app_id, &app_dir) {
            RemoveInstalledAppResult::Removed => {}
            result => self.notify_removal_failed(app_id, result),
        }
    }

    fn remove_app_bundle(&mut self, app_id: AppId, app_dir: &str) -> RemoveInstalledAppResult {
        // Before the bundle, so a failure reports the removal failed rather than the app gone
        // while its data is still on disk.
        if !self.forget_app_state(app_id) {
            return RemoveInstalledAppResult::InternalError;
        }

        match self.fs.remove(app_dir, fs::Location::System) {
            Ok(()) | Err(fs::Error::FileNotFound) => {}
            Err(e) => {
                error!("failed to remove app bundle {app_dir}: {e:?}");
                return RemoveInstalledAppResult::InternalError;
            }
        }

        match self.rescan_and_notify() {
            Ok(()) => {
                info!("removed app 0x{}", hex::encode(app_id.0));
                RemoveInstalledAppResult::Removed
            }
            Err(e) => {
                error!("failed to refresh installed apps after removing {app_dir}: {e:?}");
                RemoveInstalledAppResult::InternalError
            }
        }
    }
}

impl BlockingArchiveHandler<InstallAppArchive> for AppManagerServer {
    fn handle(
        &mut self,
        msg: InstallAppArchive,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<InstallAppArchiveResult, InstallError> {
        let installed = install::install_archive(&self.fs, &msg.path, msg.location, &self.app_registry);

        // Whether it worked or not: an install that fails partway has already removed the bundle
        // it was replacing, so the registry every reader sees is stale either way.
        let rescanned = self.rescan_and_cache();

        let install::Installed { app_id, app_dir } = match installed {
            Ok(installed) => installed,
            Err(error) => {
                error!("could not install an app from {}: {error:?}", msg.path);
                if let Ok(diff) = rescanned {
                    self.notify_app_set_changed(diff);
                }
                return Err(error);
            }
        };

        // The bundle is on disk but nothing knows about it until the rescan, so a failure here
        // leaves an app the user cannot see: report it rather than claim the install worked.
        let mut diff = rescanned.map_err(|e| {
            error!("could not refresh installed apps after installing {}: {e:?}", msg.path);
            InstallError::Internal
        })?;

        // A bundle the scan rejects (a colliding server name, say) is invisible in Settings, so
        // drop it rather than leave it eating space. An update that gets this far has already
        // removed the bundle it replaced, so the id keeps nothing but the grants and data this
        // clears.
        let Some(app_name) = self.app_registry.display_name(&app_id, &msg.locale) else {
            error!("installed app 0x{} did not enter the registry", hex::encode(app_id.0));
            self.notify_app_set_changed(diff);
            self.forget_app_state(app_id);
            if let Err(e) = self.fs.remove_if_exists(&app_dir, fs::Location::System) {
                error!("could not remove the bundle that did not register: {e:?}");
            }
            return Err(InstallError::Internal);
        };

        // The rescan diff only compares manifests
        // A successful same-manifest re-sideload still replaces bundle resources such as icon.bin, so it is
        // an AppSetChanged update too
        diff.mark_installed(app_id);
        self.notify_app_set_changed(diff);
        info!("installed app 0x{} from {}", hex::encode(app_id.0), msg.path);
        Ok(InstallAppArchiveResult { app_name })
    }
}

impl BlockingArchiveHandler<SetAppPermissionGrant> for AppManagerServer {
    fn handle(
        &mut self,
        msg: SetAppPermissionGrant,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> SetAppPermissionGrantResult {
        let app_id = match app_manager::decode_app_id_str(&msg.app_id) {
            Ok(app_id) => app_id,
            Err(e) => {
                log::warn!("SetAppPermissionGrant: invalid app id {:?}: {e:?}", msg.app_id);
                return SetAppPermissionGrantResult::AppNotFound;
            }
        };

        match msg.decision {
            PermissionGrantDecision::Allow => self.app_registry.set_permission_grant(
                app_id,
                &msg.subgroup,
                true,
                &mut self.permission_grants,
            ),
            PermissionGrantDecision::Deny => self.app_registry.set_permission_grant(
                app_id,
                &msg.subgroup,
                false,
                &mut self.permission_grants,
            ),
            PermissionGrantDecision::DenyForRun => {
                self.transient_permission_denies.entry(app_id).or_default().insert(msg.subgroup);
                SetAppPermissionGrantResult::Updated
            }
        }
    }
}

impl BlockingArchiveHandler<GetPermissionRequestInfo> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetPermissionRequestInfo,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> PermissionRequestInfoResult {
        let requesting_app_id = AppId(msg.sender_app_id);

        let server_sid = xous::SID::from_array(msg.server_sid);
        let server_name = match self.names.lookup_name_by_sid(server_sid) {
            Ok(name) => name,
            Err(xous::Error::ServerNotFound) => return PermissionRequestInfoResult::NotGrantable,
            Err(error) => {
                log::error!("GetPermissionRequestInfo: name lookup failed: {error:?}");
                return PermissionRequestInfoResult::InternalError;
            }
        };

        let result = self.app_registry.permission_request_info(
            requesting_app_id,
            &server_name,
            msg.message_id,
            &msg.locale,
            &self.permission_grants,
        );

        if let PermissionRequestInfoResult::Prompt(info) = &result {
            let denied = self
                .transient_permission_denies
                .get(&requesting_app_id)
                .is_some_and(|denies| denies.contains(&info.subgroup));
            if denied {
                return PermissionRequestInfoResult::Denied;
            }
        }
        result
    }
}

impl Server for AppManagerServer {
    fn on_start(&mut self, context: &mut ServerContext<Self>) {
        install::sweep_staged_bundles(&self.fs);
        self.rescan_and_notify().expect("Failed to scan installed apps");
        self.fs.subscribe_filesystem_events(context, fs::Location::AppData);

        xous::register_system_event_handler(SystemEvent::ChildTerminated, context.sid(), ChildCrashed::ID)
            .expect("Failed to register child terminated handler");
        xous::register_system_event_handler(SystemEvent::Disconnected, context.sid(), Disconnected::ID)
            .expect("Failed to register disconnected handler");
    }
}

impl AppManagerServer {
    pub fn new() -> anyhow::Result<Self> { Ok(Self::default()) }

    /// Rescan installed apps and install the per-server permission cache the scan built so it
    /// never lags the installed app set.
    fn rescan_and_cache(&mut self) -> anyhow::Result<registry::AppRegistryDiff> {
        let (cache, diff) = self.app_registry.scan_installed_apps(&self.fs)?;
        self.permission_grants.set_server_cache(cache);
        Ok(diff)
    }

    /// Rescan installed apps and notify subscribers about any app bundles that changed
    fn rescan_and_notify(&mut self) -> anyhow::Result<()> {
        let diff = self.rescan_and_cache()?;
        self.notify_app_set_changed(diff);
        Ok(())
    }

    /// Drop everything an app id owns besides its bundle: permission grants, stored data, and the
    /// manifest it registered with the name server. Grants and AppData are keyed by app id alone
    /// and no scan prunes them, so a bundle removed without this leaves approvals and data for
    /// whatever installs under the id next to inherit. Returns whether all of it went; the reason
    /// is logged.
    fn forget_app_state(&mut self, app_id: AppId) -> bool {
        if !self.permission_grants.remove_app_grants(app_id) {
            error!("failed to revoke permission grants for app 0x{}", hex::encode(app_id.0));
            return false;
        }
        self.transient_permission_denies.remove(&app_id);

        if let Err(e) = self.fs.remove_app_data(app_id) {
            error!("failed to remove AppData for app 0x{}: {e:?}", hex::encode(app_id.0));
            return false;
        }
        self.app_registry.clear_registered_manifest(app_id);
        true
    }
}

impl BlockingScalarHandler<LaunchAppBlocking> for AppManagerServer {
    fn handle(
        &mut self,
        LaunchAppBlocking(app_id): LaunchAppBlocking,
        sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> <LaunchAppBlocking as BlockingScalar>::Response {
        info!("PID {sender} is launching app 0x{app_id}");

        let pid = self.launch_app(app_id, sender)?;
        Ok(pid)
    }
}

impl ArchiveEventSubscriptionHandler<SubscribeAppEvents> for AppManagerServer {
    fn handle(
        &mut self,
        _msg: SubscribeAppEvents,
        subscriber: ArchiveEventSubscriber<AppEvent>,
        _context: &mut ServerContext<Self>,
    ) -> Result<(), server::Infallible> {
        debug!("New app event subscriber: {:?}", subscriber);

        self.app_event_subscribers.push(subscriber);
        Ok(())
    }
}

impl ScalarHandler<LaunchApp> for AppManagerServer {
    fn handle(&mut self, LaunchApp(app_id): LaunchApp, sender: PID, _context: &mut ServerContext<Self>) {
        info!("PID {sender} is asynchronously launching app 0x{app_id}");
        if let Err(e) = self.launch_app(app_id, sender) {
            debug!("Async launch of app 0x{app_id} failed: {e:?}");
        }
    }
}

impl BlockingArchiveHandler<GetAppName> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetAppName,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Option<String> {
        match msg {
            GetAppName::ByAppId { id, locale } => self.app_registry.app_name_by_id(&id, &locale),
            GetAppName::ByPid { pid, locale } => self.app_registry.app_name_by_pid(pid, &locale),
        }
    }
}

impl ScalarHandler<ChildCrashed> for AppManagerServer {
    fn handle(
        &mut self,
        ChildCrashed(exit_code): ChildCrashed,
        sender: PID,
        _context: &mut ServerContext<Self>,
    ) {
        let Some(&app_id) = self.app_registry.app_id_by_pid(sender) else {
            error!("Failed to get app ID for PID {sender}");
            return;
        };

        let Some(launched_by) = self.app_registry.launched_by(&app_id) else {
            error!("Failed to find launched_by PID for app ID 0x{app_id}");
            return;
        };

        let event = AppEvent::AppCrashed {
            app_id,
            pid: sender,
            launched_by,
            exit_code,
            panic_message: if exit_code != 0 { self.read_panic_message(sender) } else { None },
        };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());

        self.app_registry.terminate_app(sender);

        if self.pending_close_removals.remove(&app_id) {
            self.remove_app(app_id);
        }
    }
}

impl ScalarHandler<Disconnected> for AppManagerServer {
    fn handle(&mut self, _: Disconnected, sender: PID, _context: &mut ServerContext<Self>) {
        self.app_event_subscribers.retain(|s| s.pid() != sender);
    }
}

impl AppManagerServer {
    fn launch_app(&mut self, app_id: AppId, sender: PID) -> Result<PID, LaunchError> {
        debug!("Launching app with ID: 0x{app_id}");

        let result = self.try_launch_app(app_id, sender);
        if let Err(error) = &result {
            self.notify_launch_error(app_id, error.clone(), sender);
        }
        result
    }

    fn try_launch_app(&mut self, app_id: AppId, sender: PID) -> Result<PID, LaunchError> {
        #[cfg(keyos)]
        if let Some(pid) = xous::app_id_to_pid(&app_id)? {
            log::debug!("App 0x{app_id} already running with pid {pid}");
            self.app_registry.register_running_app(pid, app_id, sender);
            self.notify_app_launched(app_id, pid, sender);
            return Ok(pid);
        }

        self.notify_app_launching(app_id, sender);
        self.launch_new_app(app_id, sender)
    }

    fn launch_new_app(&mut self, app_id: AppId, sender: PID) -> Result<PID, LaunchError> {
        self.transient_permission_denies.remove(&app_id);

        // Allowance is dynamic: a third-party app launches only while its signer matches a
        // currently-valid publisher cert, so importing or removing a cert takes effect
        // without a rescan. Foundation-signed and hosted apps are always launchable.
        if let Some(error) = self.app_registry.launch_error(app_id, &self.third_party_cert_store.list()) {
            return Err(error);
        }

        self.register_app_resources(app_id)?;
        self.app_registry.register_app_names(app_id, &self.permission_grants)?;

        // The manifest's signed file hashes guard app.elf and the resources at launch; on the
        // simulator nothing is signed, so the staged host binary just runs.
        #[cfg(keyos)]
        let pid = crate::launch::verify_and_launch(&self.fs, &self.app_registry, app_id)?;
        #[cfg(not(keyos))]
        let pid = {
            let elf_path = self.app_registry.elf_path(app_id).ok_or(LaunchError::UnknownAppId)?;
            let host_elf = crate::launch::host_elf_path(&elf_path).ok_or(LaunchError::UnknownAppId)?;
            launch_app(&app_id, &host_elf)?
        };

        self.app_registry.register_running_app(pid, app_id, sender);

        self.notify_app_launched(app_id, pid, sender);

        Ok(pid)
    }

    fn notify_app_launching(&mut self, app_id: AppId, sender: PID) {
        debug!("Notifying app launching for app ID: 0x{app_id}");
        let event = AppEvent::AppLaunching { app_id, launched_by: sender };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn notify_app_launched(&mut self, app_id: AppId, pid: PID, sender: PID) {
        debug!("Notifying app launch for app ID: 0x{app_id}");
        let event = AppEvent::AppLaunched { app_id, pid, launched_by: sender };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn notify_launch_error(&mut self, app_id: AppId, error: LaunchError, sender: PID) {
        debug!("Notifying launch error for app ID: 0x{app_id}: {error:?}");
        let event = AppEvent::LaunchError { app_id, error, launched_by: sender };
        self.app_event_subscribers.retain(|subscriber| subscriber.send(&event).is_ok());
    }

    fn notify_app_removing(&mut self, app_id: AppId) {
        debug!("Notifying app removing for app ID: 0x{app_id}");
        let event = AppEvent::AppRemoving { app_id };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn notify_removal_failed(&mut self, app_id: AppId, result: RemoveInstalledAppResult) {
        debug!("Notifying removal failed for app ID: 0x{app_id}: {result:?}");
        let event = AppEvent::AppRemovalFailed { app_id, result };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn notify_app_set_changed(&mut self, diff: registry::AppRegistryDiff) {
        if diff.installed.is_empty() && diff.removed.is_empty() {
            return;
        }
        debug!(
            "Notifying app set changed: {} installed, {} removed",
            diff.installed.len(),
            diff.removed.len()
        );
        let event = AppEvent::AppSetChanged { installed: diff.installed, removed: diff.removed };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn notify_allowed_publishers_changed(&mut self) {
        let event = AppEvent::AllowedPublishersChanged;
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn register_app_resources(&self, app_id: AppId) -> Result<(), LaunchError> {
        if let Some(location) = self.app_registry.app_resources_location(app_id) {
            self.fs
                .register_app_resources(app_id, location.root, location.app_dir)
                .map_err(|_| LaunchError::InternalError)?;
        }

        Ok(())
    }

    fn read_panic_message(&mut self, child_pid: PID) -> Option<String> {
        if let Ok((panic_pid, panic_size)) = xous::get_panic_message(self.panic_message_buf) {
            if xous::PID::new(panic_pid) == Some(child_pid) {
                return String::from_utf8(self.panic_message_buf.as_slice()[..panic_size].to_owned()).ok();
            }
            log::debug!("Panic message PID mismatch: expected {child_pid}, got {panic_pid}");
        }
        None
    }
}

impl server::ScalarEventHandler<fs::FileSystemEvent> for AppManagerServer {
    fn handle(&mut self, msg: fs::FileSystemEvent, _sender: PID, _context: &mut ServerContext<Self>) {
        if msg.location == fs::Location::AppData && msg.event_type == fs::FileSystemEventType::Mounted {
            self.permission_grants.try_mount_app_data();
        }
    }
}
