// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

use log::{debug, error, info};
use server::{
    ArchiveEventSubscriber, ArchiveEventSubscriptionHandler, BlockingArchiveHandler, BlockingScalar,
    BlockingScalarHandler, MessageId as _, ScalarHandler, Server, ServerContext,
};
use xous::{AppId, SystemEvent, PID};

mod install;
mod launch;
mod permission_catalog;
mod permission_grants;
mod registry;
mod system_messages;
mod third_party_certs;

// Generated by build.rs from `os/app-manager/i18n/*.json` (registered in localizer.json): provides
// `tr::TrId` and `tr::lookup_id_in` for the permission subgroup labels, resolved in the request's
// locale, with no Slint dependency.
include!(concat!(env!("OUT_DIR"), "/tr.rs"));

use std::collections::{HashMap, HashSet};

use app_manager::{
    AppEvent, GetPermissionRequestInfo, GetThirdPartyCertificates, ImportThirdPartyCertificate,
    InstallAppArchive, InstallAppArchiveResult, InstallError, LaunchError, PermissionGrantDecision,
    PermissionRequestInfoResult, PreviewThirdPartyCertificate, RemoveInstalledApp, RemoveInstalledAppResult,
    RemoveThirdPartyCertificate, RemoveThirdPartyCertificateResult, SetAppPermissionGrant,
    SetAppPermissionGrantResult, ThirdPartyCertificateError, ThirdPartyCertificateInfo,
};
use app_manager::{
    GetAppIcon, GetAppName, GetQrMatchRules, InstalledAppInfo, LaunchApp, LaunchAppBlocking, ListApps,
    RefreshInstalledApps, SubscribeAppEvents,
};
use fs::adapter::FsAdapter;
use permission_grants::PermissionGrantStore;
use system_messages::{ChildCrashed, Disconnected};
use third_party_certs::ThirdPartyCertificateStore;

crypto::use_api!();
fs::use_api!();

#[cfg(not(keyos))]
use crate::launch::launch_app;
use crate::registry::AppRegistry;

pub fn listen() {
    #[cfg(not(keyos))]
    crate::launch::warn_if_app_elf_root_unset();
    server::listen(AppManagerServer::new().unwrap())
}

#[derive(server::Server)]
#[name = "os/app-manager"]
pub struct AppManagerServer {
    app_event_subscribers: Vec<ArchiveEventSubscriber<AppEvent>>,
    app_registry: AppRegistry,
    fs: FileSystem,
    permission_grants: PermissionGrantStore,
    /// Per-run "Not Now" answers, keyed by app id and permission subgroup. A subgroup here is
    /// auto-denied without re-prompting until the app relaunches, so a spammy or malicious app
    /// cannot loop the user on the same prompt (or walk through a subgroup's messages one by
    /// one). In-memory only; cleared when the app next launches.
    transient_permission_denies: HashMap<AppId, HashSet<String>>,
    third_party_cert_store: ThirdPartyCertificateStore,
    panic_message_buf: xous::MemoryRange,
    names: server::xous_names::XousNames,
}

impl Default for AppManagerServer {
    fn default() -> Self {
        let panic_message_buf =
            xous::map_memory(None, None, 0x1000, xous::MemoryFlags::W | xous::MemoryFlags::POPULATE)
                .expect("Failed to allocate panic message buffer");
        let fs = FileSystem::default();

        Self {
            app_event_subscribers: Vec::default(),
            app_registry: AppRegistry::default(),
            permission_grants: PermissionGrantStore::default(),
            transient_permission_denies: HashMap::new(),
            third_party_cert_store: ThirdPartyCertificateStore::new(fs.clone()),
            fs,
            panic_message_buf,
            names: server::xous_names::XousNames::new().expect("xous-names must be reachable"),
        }
    }
}

impl BlockingArchiveHandler<GetQrMatchRules> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetQrMatchRules,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Vec<app_manager::AppQrMatchRules> {
        self.app_registry.qr_match_rules(&msg.app_ids, &self.third_party_cert_store.list())
    }
}

impl BlockingArchiveHandler<ListApps> for AppManagerServer {
    fn handle(
        &mut self,
        msg: ListApps,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Vec<InstalledAppInfo> {
        self.app_registry.list_apps(
            &msg.locale,
            &self.third_party_cert_store.list(),
            &msg.filter,
            &self.permission_grants,
        )
    }
}

impl BlockingScalarHandler<RefreshInstalledApps> for AppManagerServer {
    fn handle(
        &mut self,
        _msg: RefreshInstalledApps,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<(), app_manager::AppManagerError> {
        self.rescan_and_cache().map_err(|e| {
            error!("failed to refresh installed apps: {e:?}");
            app_manager::AppManagerError::InternalError
        })
    }
}

impl BlockingArchiveHandler<GetAppIcon> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetAppIcon,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Option<Vec<u8>> {
        let app_id = match app_manager::decode_app_id_str(&msg.app_id) {
            Ok(app_id) => app_id,
            Err(e) => {
                log::warn!("GetAppIcon: invalid app id {:?}: {e:?}", msg.app_id);
                return None;
            }
        };
        self.app_registry.app_icon_bytes(&self.fs, app_id, msg.variant)
    }
}

impl BlockingArchiveHandler<GetThirdPartyCertificates> for AppManagerServer {
    fn handle(
        &mut self,
        _msg: GetThirdPartyCertificates,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Vec<ThirdPartyCertificateInfo> {
        self.third_party_cert_store.list()
    }
}

impl BlockingArchiveHandler<PreviewThirdPartyCertificate> for AppManagerServer {
    fn handle(
        &mut self,
        msg: PreviewThirdPartyCertificate,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<ThirdPartyCertificateInfo, ThirdPartyCertificateError> {
        self.third_party_cert_store.preview(&msg.certificate_pem)
    }
}

impl BlockingArchiveHandler<ImportThirdPartyCertificate> for AppManagerServer {
    fn handle(
        &mut self,
        msg: ImportThirdPartyCertificate,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<ThirdPartyCertificateInfo, ThirdPartyCertificateError> {
        let cert = self.third_party_cert_store.import(&msg.certificate_pem, &msg.expected_fingerprint)?;
        self.notify_allowed_publishers_changed();
        Ok(cert)
    }
}

impl BlockingArchiveHandler<RemoveThirdPartyCertificate> for AppManagerServer {
    fn handle(
        &mut self,
        msg: RemoveThirdPartyCertificate,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> RemoveThirdPartyCertificateResult {
        // Only block removal while the certificate is still allowed. An expired cert can
        // no longer launch the app that was signed with it, so the user must be able to
        // delete the stale entry even though an installed app still references that key.
        if let Some(cert) = self.third_party_cert_store.allowed(&msg.fingerprint) {
            if let Some(app_name) =
                self.app_registry.app_name_requiring_third_party_key(&cert.public_key, &msg.locale)
            {
                return RemoveThirdPartyCertificateResult::AppRequiresKey(app_name);
            }
        }

        match self.third_party_cert_store.remove(&msg.fingerprint) {
            Ok(true) => {
                self.notify_allowed_publishers_changed();
                RemoveThirdPartyCertificateResult::Removed
            }
            Ok(false) => RemoveThirdPartyCertificateResult::NotFound,
            Err(e) => {
                error!("failed to remove third-party certificate: {e:?}");
                RemoveThirdPartyCertificateResult::InternalError
            }
        }
    }
}

impl BlockingArchiveHandler<RemoveInstalledApp> for AppManagerServer {
    fn handle(
        &mut self,
        msg: RemoveInstalledApp,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> RemoveInstalledAppResult {
        let app_id = msg.app_id;

        if self.app_registry.is_running(&app_id) {
            return RemoveInstalledAppResult::Running;
        }

        // Removing the Legacy emulator wipes every Flux child's AppData below. A child can still
        // be running even when the emulator process itself was reaped or crashed, so refuse while
        // any child is running rather than delete its NVM out from under it.
        if app_id == crate::registry::FLUX_EMULATOR_APP_ID
            && self.app_registry.flux_child_app_ids().iter().any(|id| self.app_registry.is_running(id))
        {
            return RemoveInstalledAppResult::Running;
        }

        let Some(app_dir) = self.app_registry.removable_bundle_dir(app_id) else {
            return if self.app_registry.contains_app(app_id) {
                RemoveInstalledAppResult::NotSideloaded
            } else {
                RemoveInstalledAppResult::NotFound
            };
        };

        info!("removing app 0x{} from {app_dir}", hex::encode(app_id.0));

        // Before the bundle, so a failure reports the removal failed rather than the app gone
        // while its data is still on disk.
        if !self.forget_app_state(app_id) {
            return RemoveInstalledAppResult::InternalError;
        }

        // Flux children persist their NVM to their own AppData (nvm.bin), which removing
        // the emulator does not otherwise reach: the bundle removal below deletes only the
        // built-in children's bundles, and sideloaded children live under a separate root.
        if app_id == crate::registry::FLUX_EMULATOR_APP_ID {
            for child_id in self.app_registry.flux_child_app_ids() {
                if !self.forget_app_state(child_id) {
                    return RemoveInstalledAppResult::InternalError;
                }
            }
        }

        match self.fs.remove(&app_dir, fs::Location::System) {
            Ok(()) | Err(fs::Error::FileNotFound) => {}
            Err(e) => {
                error!("failed to remove app bundle {app_dir}: {e:?}");
                return RemoveInstalledAppResult::InternalError;
            }
        }

        match self.rescan_and_cache() {
            Ok(()) => {
                info!("removed app 0x{}", hex::encode(app_id.0));
                RemoveInstalledAppResult::Removed
            }
            Err(e) => {
                error!("failed to refresh installed apps after removing {app_dir}: {e:?}");
                RemoveInstalledAppResult::InternalError
            }
        }
    }
}

impl BlockingArchiveHandler<InstallAppArchive> for AppManagerServer {
    fn handle(
        &mut self,
        msg: InstallAppArchive,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Result<InstallAppArchiveResult, InstallError> {
        let installed = install::install_archive(&self.fs, &msg.path, msg.location, &self.app_registry);

        // Whether it worked or not: an install that fails partway has already removed the bundle
        // it was replacing, so the registry every reader sees is stale either way.
        let rescanned = self.rescan_and_cache();

        let install::Installed { app_id, app_dir } =
            installed.inspect_err(|e| error!("could not install an app from {}: {e:?}", msg.path))?;

        // The bundle is on disk but nothing knows about it until the rescan, so a failure here
        // leaves an app the user cannot see: report it rather than claim the install worked.
        if let Err(e) = rescanned {
            error!("could not refresh installed apps after installing {}: {e:?}", msg.path);
            return Err(InstallError::Internal);
        }

        // A bundle the scan rejects (a colliding server name, say) is invisible in Settings, so
        // drop it rather than leave it eating space. An update that gets this far has already
        // removed the bundle it replaced, so the id keeps nothing but the grants and data this
        // clears.
        let Some(app_name) = self.app_registry.display_name(&app_id, &msg.locale) else {
            error!("installed app 0x{} did not enter the registry", hex::encode(app_id.0));
            self.forget_app_state(app_id);
            if let Err(e) = self.fs.remove_if_exists(&app_dir, fs::Location::System) {
                error!("could not remove the bundle that did not register: {e:?}");
            }
            return Err(InstallError::Internal);
        };

        info!("installed app 0x{} from {}", hex::encode(app_id.0), msg.path);
        Ok(InstallAppArchiveResult { app_name })
    }
}

impl BlockingArchiveHandler<SetAppPermissionGrant> for AppManagerServer {
    fn handle(
        &mut self,
        msg: SetAppPermissionGrant,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> SetAppPermissionGrantResult {
        let app_id = match app_manager::decode_app_id_str(&msg.app_id) {
            Ok(app_id) => app_id,
            Err(e) => {
                log::warn!("SetAppPermissionGrant: invalid app id {:?}: {e:?}", msg.app_id);
                return SetAppPermissionGrantResult::AppNotFound;
            }
        };

        match msg.decision {
            PermissionGrantDecision::Allow => self.app_registry.set_permission_grant(
                app_id,
                &msg.subgroup,
                true,
                &mut self.permission_grants,
            ),
            PermissionGrantDecision::Deny => self.app_registry.set_permission_grant(
                app_id,
                &msg.subgroup,
                false,
                &mut self.permission_grants,
            ),
            PermissionGrantDecision::DenyForRun => {
                self.transient_permission_denies.entry(app_id).or_default().insert(msg.subgroup);
                SetAppPermissionGrantResult::Updated
            }
        }
    }
}

impl BlockingArchiveHandler<GetPermissionRequestInfo> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetPermissionRequestInfo,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> PermissionRequestInfoResult {
        let requesting_app_id = AppId(msg.sender_app_id);

        let server_sid = xous::SID::from_array(msg.server_sid);
        let server_name = match self.names.lookup_name_by_sid(server_sid) {
            Ok(name) => name,
            Err(xous::Error::ServerNotFound) => return PermissionRequestInfoResult::NotGrantable,
            Err(error) => {
                log::error!("GetPermissionRequestInfo: name lookup failed: {error:?}");
                return PermissionRequestInfoResult::InternalError;
            }
        };

        let result = self.app_registry.permission_request_info(
            requesting_app_id,
            &server_name,
            msg.message_id,
            &msg.locale,
            &self.permission_grants,
        );

        if let PermissionRequestInfoResult::Prompt(info) = &result {
            let denied = self
                .transient_permission_denies
                .get(&requesting_app_id)
                .is_some_and(|denies| denies.contains(&info.subgroup));
            if denied {
                return PermissionRequestInfoResult::Denied;
            }
        }
        result
    }
}

impl Server for AppManagerServer {
    fn on_start(&mut self, context: &mut ServerContext<Self>) {
        install::sweep_staged_bundles(&self.fs);
        self.rescan_and_cache().expect("Failed to scan installed apps");
        self.fs.subscribe_filesystem_events(context, fs::Location::AppData);

        xous::register_system_event_handler(SystemEvent::ChildTerminated, context.sid(), ChildCrashed::ID)
            .expect("Failed to register child terminated handler");
        xous::register_system_event_handler(SystemEvent::Disconnected, context.sid(), Disconnected::ID)
            .expect("Failed to register disconnected handler");
    }
}

impl AppManagerServer {
    pub fn new() -> anyhow::Result<Self> { Ok(Self::default()) }

    /// Rescan installed apps, install the per-server permission cache the scan built so it never
    /// lags the installed app set, and notify subscribers of any app the scan added or dropped
    fn rescan_and_cache(&mut self) -> anyhow::Result<()> {
        let (cache, diff) = self.app_registry.scan_installed_apps(&self.fs)?;
        self.permission_grants.set_server_cache(cache);
        self.notify_app_set_changed(diff);
        Ok(())
    }

    /// Drop everything an app id owns besides its bundle: permission grants, stored data, and the
    /// manifest it registered with the name server. Grants and AppData are keyed by app id alone
    /// and no scan prunes them, so a bundle removed without this leaves approvals and data for
    /// whatever installs under the id next to inherit. Returns whether all of it went; the reason
    /// is logged.
    fn forget_app_state(&mut self, app_id: AppId) -> bool {
        if !self.permission_grants.remove_app_grants(app_id) {
            error!("failed to revoke permission grants for app 0x{}", hex::encode(app_id.0));
            return false;
        }
        self.transient_permission_denies.remove(&app_id);

        if let Err(e) = self.fs.remove_app_data(app_id) {
            error!("failed to remove AppData for app 0x{}: {e:?}", hex::encode(app_id.0));
            return false;
        }
        self.app_registry.clear_registered_manifest(app_id);
        true
    }
}

impl BlockingScalarHandler<LaunchAppBlocking> for AppManagerServer {
    fn handle(
        &mut self,
        LaunchAppBlocking(app_id): LaunchAppBlocking,
        sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> <LaunchAppBlocking as BlockingScalar>::Response {
        info!("PID {sender} is launching app 0x{app_id}");

        let pid = self.launch_app(app_id, sender)?;
        Ok(pid)
    }
}

impl ArchiveEventSubscriptionHandler<SubscribeAppEvents> for AppManagerServer {
    fn handle(
        &mut self,
        _msg: SubscribeAppEvents,
        subscriber: ArchiveEventSubscriber<AppEvent>,
        _context: &mut ServerContext<Self>,
    ) -> Result<(), server::Infallible> {
        debug!("New app event subscriber: {:?}", subscriber);

        self.app_event_subscribers.push(subscriber);
        Ok(())
    }
}

impl ScalarHandler<LaunchApp> for AppManagerServer {
    fn handle(&mut self, LaunchApp(app_id): LaunchApp, sender: PID, _context: &mut ServerContext<Self>) {
        info!("PID {sender} is asynchronously launching app 0x{app_id}");
        if let Err(e) = self.launch_app(app_id, sender) {
            if let Some(s) = self.app_event_subscribers.iter().find(|s| s.pid() == sender) {
                let event = AppEvent::LaunchError { app_id, error: e };
                if s.send(&event).is_err() {
                    error!("Failed to send launch error to subscriber PID {sender}");
                }
            }
        }
    }
}

impl BlockingArchiveHandler<GetAppName> for AppManagerServer {
    fn handle(
        &mut self,
        msg: GetAppName,
        _sender: PID,
        _context: &mut ServerContext<Self>,
    ) -> Option<String> {
        match msg {
            GetAppName::ByAppId { id, locale } => self.app_registry.app_name_by_id(&id, &locale),
            GetAppName::ByPid { pid, locale } => self.app_registry.app_name_by_pid(pid, &locale),
        }
    }
}

impl ScalarHandler<ChildCrashed> for AppManagerServer {
    fn handle(
        &mut self,
        ChildCrashed(exit_code): ChildCrashed,
        sender: PID,
        _context: &mut ServerContext<Self>,
    ) {
        let Some(app_id) = self.app_registry.app_id_by_pid(sender) else {
            error!("Failed to get app ID for PID {sender}");
            return;
        };

        let Some(launched_by) = self.app_registry.launched_by(app_id) else {
            error!("Failed to find launched_by PID for app ID 0x{app_id}");
            return;
        };

        let event = AppEvent::AppCrashed {
            app_id: *app_id,
            pid: sender,
            launched_by,
            exit_code,
            panic_message: if exit_code != 0 { self.read_panic_message(sender) } else { None },
        };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());

        self.app_registry.terminate_app(sender);
    }
}

impl ScalarHandler<Disconnected> for AppManagerServer {
    fn handle(&mut self, _: Disconnected, sender: PID, _context: &mut ServerContext<Self>) {
        self.app_event_subscribers.retain(|s| s.pid() != sender);
    }
}

impl AppManagerServer {
    fn launch_app(&mut self, app_id: AppId, sender: PID) -> Result<PID, LaunchError> {
        debug!("Launching app with ID: 0x{app_id}");

        #[cfg(keyos)]
        if let Some(pid) = xous::app_id_to_pid(&app_id)? {
            log::debug!("App 0x{app_id} already running with pid {pid}");
            self.app_registry.register_running_app(pid, app_id, sender);
            self.notify_app_launched(app_id, pid, sender);
            return Ok(pid);
        }

        self.transient_permission_denies.remove(&app_id);

        // The registry tracks the bundle's fs `app.elf` path; the device launches
        // it from the image, the simulator from the staged host binary.
        let elf_path = self.app_registry.elf_path(app_id).ok_or(LaunchError::UnknownAppId)?;

        // Allowance is dynamic: a sideloaded app launches only while its signer matches a
        // currently-valid publisher cert, so importing or removing a cert takes effect
        // without a rescan. Built-in and hosted apps are always launchable.
        if let Some(error) = self.app_registry.launch_error(app_id, &self.third_party_cert_store.list()) {
            return Err(error);
        }

        self.register_app_resources(app_id)?;
        self.app_registry.register_app_names(app_id, &self.permission_grants)?;

        // The manifest's signed file hashes guard app.elf and the resources at launch; on the
        // simulator nothing is signed, so the staged host binary just runs.
        #[cfg(keyos)]
        let pid = {
            let file_hashes = self.app_registry.file_hashes(app_id).ok_or(LaunchError::UnknownAppId)?;
            let signer = self.app_registry.elf_signer(app_id);
            crate::launch::verify_and_launch(&self.fs, &app_id, &elf_path, &file_hashes, signer)?
        };
        #[cfg(not(keyos))]
        let pid = {
            let host_elf = crate::launch::host_elf_path(&elf_path).ok_or(LaunchError::UnknownAppId)?;
            launch_app(&app_id, &host_elf)?
        };

        self.app_registry.register_running_app(pid, app_id, sender);

        self.notify_app_launched(app_id, pid, sender);

        Ok(pid)
    }

    fn notify_app_launched(&mut self, app_id: AppId, pid: PID, sender: PID) {
        debug!("Notifying app launch for app ID: 0x{app_id}");
        let event = AppEvent::AppLaunched { app_id, pid, launched_by: sender };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn notify_app_set_changed(&mut self, diff: registry::AppRegistryDiff) {
        if diff.installed.is_empty() && diff.removed.is_empty() {
            return;
        }
        debug!(
            "Notifying app set changed: {} installed, {} removed",
            diff.installed.len(),
            diff.removed.len()
        );
        let event = AppEvent::AppSetChanged { installed: diff.installed, removed: diff.removed };
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn notify_allowed_publishers_changed(&mut self) {
        let event = AppEvent::AllowedPublishersChanged;
        self.app_event_subscribers.retain(|s| s.send(&event).is_ok());
    }

    fn register_app_resources(&self, app_id: AppId) -> Result<(), LaunchError> {
        if let Some(location) = self.app_registry.app_resources_location(app_id) {
            self.fs
                .register_app_resources(app_id, location.root, location.app_dir)
                .map_err(|_| LaunchError::InternalError)?;
        }

        Ok(())
    }

    fn read_panic_message(&mut self, child_pid: PID) -> Option<String> {
        if let Ok((panic_pid, panic_size)) = xous::get_panic_message(self.panic_message_buf) {
            if xous::PID::new(panic_pid) == Some(child_pid) {
                return String::from_utf8(self.panic_message_buf.as_slice()[..panic_size].to_owned()).ok();
            }
            log::debug!("Panic message PID mismatch: expected {child_pid}, got {panic_pid}");
        }
        None
    }
}

impl server::ScalarEventHandler<fs::FileSystemEvent> for AppManagerServer {
    fn handle(&mut self, msg: fs::FileSystemEvent, _sender: PID, _context: &mut ServerContext<Self>) {
        if msg.location == fs::Location::AppData && msg.event_type == fs::FileSystemEventType::Mounted {
            self.permission_grants.try_mount_app_data();
        }
    }
}
