# SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

appId = "0x38a8f01a9eef414b7c2c6729a6b0c306"

[appName]
en = "Ethereum"

[appDescription]
en = "Ethereum app running on Flux."

[permissions]
"os/gui-app-emu-flux" = ["SvcCall", "SendSeph", "RecvSeph", "SyscallBuffer"]
