// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Size } from "@ui/theme.slint";
import { Button, NavHeader, BasePage, ButtonSection, SeedWords, QrPages } from "@ui/widgets.slint";
import { Navigate } from "../../gen/navigate.slint";
import { Callbacks } from "../../globals.slint";
import { ViewSeedWordsProps } from "./props.slint";

export component ViewSeedWordsPage inherits BasePage {
    in property <ViewSeedWordsProps> props;

    private property <bool> qr-view: false;

    VerticalLayout {
        NavHeader {
            title: "Seed Words"; // TODO: i18n
            right-icon: qr-view ? "list" : "scan-qr";
            clicked => {
                Navigate.backward();
            }
            right-clicked => {
                qr-view = !qr-view;
            }
        }

        VerticalLayout {
            padding-top: qr-view ? Size.sz2 : Size.sz10;
            padding-bottom: Size.sz4;

            if !qr-view: SeedWords {
                words: Callbacks.get-seed-words();
            }

            if qr-view: QrPages {
                model: [
                    { code: Callbacks.get-standard-seed-qr(), header: "Standard SeedQR", // TODO: i18n
                    },
                    { code: Callbacks.get-compact-seed-qr(), header: "Compact SeedQR", // TODO: i18n
                    },
                ];
            }

            ButtonSection {
                padding: Size.sz6;
                Button {
                    label: "Done"; // TODO: i18n
                    clicked => {
                        Navigate.backward();
                    }
                }
            }
        }
    }
}
