// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

export global AboutGlobal {
    in property <string> serial-number: "";
    in property <string> board-revision: "";
    in property <string> keyos-version: "";
    in property <string> bootloader-version: "";
    in property <string> ble-firmware-version: "";
    in property <string> ble-bootloader-version: "";
    in property <string> master-fingerprint: "";
    in property <string> reversed-fingerprint: "";
}
