manifestVersion = "0"
appId = "0xbf5cdfbfda7e85b5253ff268d32ea957"
syscall = ["CreateProcess", "GetPanicMessage"]
extends = "../../api/app-manager"

[appName]
en = "App Manager"

[servers."os/app-manager"]
ChildCrashed = { id = 64, type = "scalar" }
Disconnected = { id = 65, type = "scalar" }

[permissions]
template = ["fs-generic", "crypto-sha"]
"os/crypto" = ["ShaSetContext", "ShaUpdate", "ShaGetContext", "ShaDrop"]
"os/fs" = [
    "GetSystemReadAccess",
    "GetSystemWriteAccess",
    "GetSystemAppDataReadAccess",
    "GetSystemAppDataWriteAccess",
    "Remove",
    "RemoveAppData",
    "RegisterAppResources",
]
"os/nameserver" = ["AddManifest", "RemoveManifest"]
