// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { BasePage } from "@ui/widgets.slint";
import { SeedEntry } from "@ui/pages.slint";
import { Navigate } from "../../gen/navigate.slint";
import { Callbacks } from "../../globals.slint";
import { SeedImportProps } from "./props.slint";
import { TR2, TrId } from "../../gen/tr.slint";

export component SeedImportPage inherits BasePage {
    in property <SeedImportProps> props;

    entry := SeedEntry {
        strings: {
            title: TR2.lookup(TrId.RecoverWordsTitle),
            expand: TR2.lookup(TrId.CommonRecoverWordsExpandTo24Word),
            error: TR2.lookup(TrId.CommonRecoverWordsIncorrectTryAgain),
            submit: TR2.lookup(TrId.CommonButtonConfirm),
        };
        placeholder-for(i) => {
            return TR2.format(TrId.OnboardingRecoverWordsFillerText, ["\{i + 1}"]);
        }
        submit(ws) => {
            if (Callbacks.confirm-seed-import(ws)) {
                Navigate.main({ replace: true });
            }
        }
        back => {
            Navigate.backward();
        }
    }

    init => {
        entry.reset();
    }
}
