// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Button, ButtonSection, JumboIconPageBody } from "@ui/widgets.slint";
import { SeedEntry } from "@ui/pages.slint";
import { OnboardingBasePage } from "../../../../widgets/base-page.slint";
import { Navigate } from "../../../../gen/navigate.slint";
import { TR2, TrId } from "../../../../gen/tr.slint";
import {
    OnboardingCallbacks,
    MasterSeedState,
    SeedGlobal,
} from "../../../../onboarding-callbacks.slint";
import {
    RestoreSeedLoading,
    RestoreSuccessContent,
    RestoreFailed,
} from "../../../../widgets/restore-seed.slint";

component Success inherits JumboIconPageBody {
    RestoreSuccessContent { }

    ButtonSection {
        Button {
            label: TR2.lookup(TrId.CommonButtonContinue);
            importance: primary;
            clicked => {
                if (SeedGlobal.is-master-key-recovery) {
                    OnboardingCallbacks.finish-onboarding();
                } else {
                    Navigate.restore-magic-backup({ });
                }
            }
        }
    }
}

export component RestoreSeedWordsPage inherits OnboardingBasePage {
    property <MasterSeedState> state <=> SeedGlobal.master-seed-state;

    if state == MasterSeedState.Idle: SeedEntry {
        strings: {
            title: TR2.lookup(TrId.RecoverWordsTilte),
            expand: TR2.lookup(TrId.CommonRecoverWordsExpandTo24Word),
            error: TR2.lookup(TrId.CommonRecoverWordsIncorrectTryAgain),
            submit: TR2.lookup(TrId.CommonButtonContinue),
        };
        placeholder-for(i) => {
            return TR2.format(TrId.RecoverWordsFillerText, ["\{i + 1}"]);
        }
        validate-word(w) => {
            return SeedGlobal.validate-seed-word(w);
        }
        validate-seed(ws) => {
            return SeedGlobal.validate-full-seed(ws);
        }
        submit(ws) => {
            SeedGlobal.restore-from-seed-words(ws);
        }
        back => {
            Navigate.backward();
        }
    }
    if state == MasterSeedState.SavingToSE || state == MasterSeedState.EncryptingFs: RestoreSeedLoading { }
    if state == MasterSeedState.Success: Success { }
    if state == MasterSeedState.Failed: RestoreFailed {
        // TODO: formalize or remove
        title: "Failed to restore Master Seed";
        retry => {
            state = MasterSeedState.Idle;
        }
    }
}
