// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { BasePage } from "@ui/widgets.slint";
import { SeedEntry } from "@ui/pages.slint";
import { Callbacks as CB } from "../../callbacks.slint";
import { Navigate } from "../../gen/navigate.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { InputSeedProps } from "./props.slint";

export component InputSeedPage inherits BasePage {
    in property <InputSeedProps> props;

    entry := SeedEntry {
        strings: {
            title: TR2.lookup(TrId.ManualImportImportSeedWords),
            expand: TR2.lookup(TrId.CommonRecoverWordsExpandTo24Word),
            error: TR2.lookup(TrId.CommonRecoverWordsIncorrectTryAgain),
            submit: TR2.lookup(TrId.CommonButtonContinue),
        };
        placeholder-for(_i) => {
            return "";
        }
        validate-word(word) => {
            return CB.validate-seed-word(word);
        }
        validate-seed(words) => {
            return CB.validate-full-seed(words);
        }
        submit(words) => {
            CB.set-pending-imported-seed(
                CB.words-to-entropy(words),
                CB.get-seed-fingerprint(words),
            );
            Navigate.save-seed({ });
        }
        back => {
            CB.clear-pending-import();
            Navigate.backward();
        }
    }

    init => {
        entry.reset();
    }
}
