# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "fw-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
cosign2 = { workspace = true, default-features = false, features = ["std"] }
crypto = { workspace = true }
fs = { workspace = true }
log = "0.4.14"
secp256k1 = "0.29"
server = { path = "../../server" }
thiserror = "1.0"
xous = { path = "../../xous/xous-rs" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
