# SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: MIT

[toolchain]
channel = "nightly-2026-04-11"
components = ["rustfmt", "clippy", "rustc", "rust-src"]
targets = []
profile = "minimal"
