# SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "gui-app-entropy-test"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
log-server = { workspace = true }
slint-keyos-platform = { path = "../../slint-keyos-platform/runtime" }
trng = { path = "../../xous/trng" }

[build-dependencies]
slint-keyos-platform-build = { path = "../../slint-keyos-platform/build" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(keyos)'] }
