// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size } from "@ui/theme.slint";
import { Navigate, Animate } from "../../gen/navigate.slint";
import { IntroProps } from "./props.slint";
import {
    Button,
    Icon,
    HeadingLg,
    TextMd,
    WrappedIcon,
    ButtonSection,
    ShieldPage,
    ContentSection,
} from "@ui/widgets.slint";
import { Global, Callbacks } from "../../globals.slint";
import { TR2, TrId } from "../../gen/tr.slint";

export component IntroPage inherits ShieldPage {
    in property <IntroProps> props;

    ContentSection {
        VerticalLayout {
            vertical-stretch: 1;
            alignment: center;
            spacing: Size.sz6;

            HorizontalLayout {
                alignment: center;

                WrappedIcon {
                    name: "jumbo-circle";
                    inner-icon: "legacy";
                }
            }

            VerticalLayout {
                alignment: center;
                spacing: Size.sz2;

                HeadingLg {
                    text: TR2.lookup(TrId.IntroHeader);
                    horizontal-alignment: center;
                }

                TextMd {
                    text: TR2.lookup(TrId.IntroContent);
                    horizontal-alignment: center;
                    color: Palette.content-tertiary;
                    wrap: word-wrap;
                }
            }
        }
    }

    ButtonSection {
        Button {
            label: TR2.lookup(TrId.IntroLoadFromVault);
            icon: "shield";
            importance: tertiary;
            enabled: false;
        }

        Button {
            label: TR2.lookup(TrId.IntroEnterSeedWords);
            icon: "edit";
            importance: secondary;
            clicked => {
                Navigate.seed-import({ });
            }
        }

        Button {
            label: TR2.lookup(TrId.IntroCreateNewSeed);
            icon: "plus";
            importance: primary;
            clicked => {
                Callbacks.derive-new-seed();
            }
        }
    }
}
