// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size } from "@ui/theme.slint";
import { Navigate, Animate } from "../../gen/navigate.slint";
import { IntroProps } from "./props.slint";
import { Button, Icon, HeadingLg, TextMd, WrappedIcon, ButtonSection, ShieldPage, ContentSection } from "@ui/widgets.slint";
import { Global, Callbacks } from "../../globals.slint";

export component IntroPage inherits ShieldPage {
    in property <IntroProps> props;

    ContentSection {
        VerticalLayout {
            vertical-stretch: 1;
            alignment: center;
            spacing: Size.sz6;

            HorizontalLayout {
                alignment: center;

                WrappedIcon {
                    name: "jumbo-circle";
                    inner-icon: "legacy";
                }
            }

            VerticalLayout {
                alignment: center;
                spacing: Size.sz2;

                HeadingLg {
                    text: @tr("Welcome to Legacy Mode");
                    horizontal-alignment: center;
                }

                TextMd {
                    text: "Legacy Mode lets you manage assets beyond Bitcoin, directly on Passport Prime. Create a new seed or import one from an existing wallet to get started.";
                    horizontal-alignment: center;
                    color: Palette.content-tertiary;
                    wrap: word-wrap;
                }
            }
        }
    }

    ButtonSection {
        Button {
            label: @tr("Load from Vault");
            icon: "shield";
            importance: tertiary;
            enabled: false;
        }

        Button {
            label: @tr("Enter 24 words");
            icon: "edit";
            importance: secondary;
            clicked => {
                Navigate.seed-import({ });
            }
        }

        Button {
            label: @tr("Create new Seed");
            icon: "plus";
            importance: primary;
            clicked => {
                Callbacks.derive-new-seed();
            }
        }
    }
}
