// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size } from "@ui/theme.slint";
import {
    Button,
    NavHeader,
    Icon,
    HeadingLg,
    TextMd,
    JumboIconPageBody,
    WrappedIcon,
    ButtonSection,
    ContentSection,
} from "@ui/widgets.slint";
import { Navigate, Animate } from "../../gen/navigate.slint";
import { Callbacks } from "../../globals.slint";
import { SeedDeriveProps } from "./props.slint";
import { TR2, TrId } from "../../gen/tr.slint";

export component SeedDerivePage inherits JumboIconPageBody {
    in property <SeedDeriveProps> props;

    ContentSection {
        HorizontalLayout {
            alignment: center;

            WrappedIcon {
                name: "jumbo-circle";
                inner-icon: "check";
            }
        }

        HeadingLg {
            text: TR2.lookup(TrId.CreateSeedHeader);
            horizontal-alignment: center;
        }

        TextMd {
            text: TR2.lookup(TrId.CreateSeedContent);
            horizontal-alignment: center;
            color: Palette.content-tertiary;
            wrap: word-wrap;
        }
    }

    ButtonSection {
        Button {
            label: TR2.lookup(TrId.CommonButtonContinue);
            importance: primary;
            clicked => {
                if (Callbacks.confirm-seed-derive()) {
                    Navigate.main({ replace: true });
                }
            }
        }
    }
}
