# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 immz https://github.com/immz4
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "gui-app-authenticator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
argon2 = "0.5.3"
base32 = "0.4"
base64 = "0.22.1"
crypto = { workspace = true }
csv = "1.3.1"
fs = { workspace = true }
fuzzy-filter = "0.1.0"
i18n = { path = "../../i18n" }
log = "0.4.14"
log-server = { package = "xous-api-log", path = "../../xous/api/log" }
ordered-table = { path = "../../utils/ordered-table" }
pbkdf2 = "0.12.2"
pgp = { version = "0.20.0", default-features = false }
prost = "0.14.3"
scrypt = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
server = { path = "../../server" }
sha2 = "0.10.9"
slint-keyos-platform = { path = "../../slint-keyos-platform/runtime" }
subtle = { version = "2.6", default-features = false }
thiserror = "1.0"
totp-rs = { version = "5.6.0", features = ["otpauth", "serde_support"] }
url = "2.5.8"
urlencoding = "2.1.3"
xous = { workspace = true }
zip = { version = "2.2.0", default-features = false }

[build-dependencies]
prost-build = "0.14.3"
slint-keyos-platform-build = { path = "../../slint-keyos-platform/build" }

[dev-dependencies]
hex-literal = "0.4"
